### ISSUE TITLE
All editors need access to this repo

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#1]
Hi @cmungall or other owners,

the phenotype editors that have to change the imports files need access to the [upheno-repository](https://github.com/obophenotype/upheno).

Also, several users are owners and others are not. It may be easier to add more people to owners (I can't see the pattern who became owner and who not). Anyway we need access to upheno.

Thanks,
Seb

**Comment by cmungall** [comment]
added mp and hp teams, done!
