### ISSUE TITLE
Make Stenosis terms consistent

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#108]
Originally reported on Google Code with ID 107
```
Stenosis terms should use:
'has part' some 
    (constricted
     and ('inheres in' some [UBERON])
     and ('has modifier' some abnormal))


```

Reported by `vasilevs@ohsu.edu` on 2015-02-23 16:43:13

**Comment by drseb** [comment]
quick check in HP/MP. looks good. please reopen if there are still problems
