### ISSUE TITLE
how to model 'abnormal amount'?

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#111]
Originally reported on Google Code with ID 110

```
The notes in the best practices doc (https://docs.google.com/document/d/1LOYQ6pOlvapzJhHbSA_Rb3aZYylXZ564B78jiysvB-U/edit#heading=h.rs7nj110pz4n)
are inconsistent with what is in the ontology for the patterns for "abnormal amount"

Should it be:
has part' some (amount and ('inheres in' some 'cell/anatomy') and ('has modifier' some
abnormal))

?


```

Reported by `vasilevs@ohsu.edu` on 2015-02-25 22:39:06

**Comment by drseb** [comment]
@nicolevasilevsky is there any news on this? have we decided and implemented?

**Comment by nicolevasilevsky** [comment]
I think this has been resolved, we have patterns for abnormal level of chemical, abnormal level of molecular entity and these all use the pattern above
