### ISSUE TITLE
~3K missing sextuples in zp mappings

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#118]
Originally reported on Google Code with ID 117
```
~3K missing sextuples in zp mappings (see attached).  determined from testing dipper
processing today.
```

Reported by `nicole.l.washington` on 2015-04-10 00:17:05

<hr>
 * *Attachment: [missing_sextuples_zfin_20150409.txt](https://storage.googleapis.com/google-code-attachments/phenotype-ontologies/issue-117/comment-0/missing_sextuples_zfin_20150409.txt)*

**Comment by drseb** [comment]
I hope I have dealt with these issues. See https://github.com/sba1/bio-ontology-zp/issues?q=is%3Aissue+is%3Aclosed
