### ISSUE TITLE
Add axiom annotation to equivalence axioms derived from lexical entity matching

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#12]
Originally reported on Google Code with ID 11
```
It should be easy to identify equivalencies in Protege that derive from the entity matching
pipeline
```

Reported by `cmungall` on 2014-03-28 14:54:15

**Comment by drseb** [comment]
chris can you add this? if not please close this issue.

**Comment by cmungall** [comment]
Looks like this was done a while ago; annotated with `source="textmatch"`
