### ISSUE TITLE
add VT

### ISSUE THREAD

**Issue by nlwashington** [obophenotype/upheno#140]
please incorporate VT terms.

**Comment by nlwashington** [comment]
accurate performance will depends on #142

**Comment by nlwashington** [comment]
also should port code from old googlecode site makefile:
https://code.google.com/p/phenotype-ontologies/source/browse/trunk/src/ontology/vt/Makefile

**Comment by drseb** [comment]
vt is in import-chain. I guess it is ok to close this issue then
