### ISSUE TITLE
Vertebrate.owl classes

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#153]
Hi,

is it correct that the following OWL-classes are declared in [vertebrate.owl](https://github.com/obophenotype/upheno/blob/master/vertebrate.owl) ? What's the purpose of these? @nicolevasilevsky @cmungall 

    <owl:Class rdf:about="&obo;UPHENO_0000501">
        <rdfs:label>accelerated feather growth</rdfs:label>
    </owl:Class>
    
    <owl:Class rdf:about="&obo;UPHENO_0000502">
        <rdfs:label>curved upper beak</rdfs:label>
    </owl:Class>
    
    <owl:Class rdf:about="&obo;UPHENO_0000503">
        <rdfs:label>short upper beak</rdfs:label>
    </owl:Class>
    
    <owl:Class rdf:about="&obo;UPHENO_0000504">
        <rdfs:label>absent feather barbule</rdfs:label>
    </owl:Class>
    
    <owl:Class rdf:about="&obo;UPHENO_0000505">
        <rdfs:label>decreased wing length</rdfs:label>
    </owl:Class>
    
    <owl:Class rdf:about="&obo;UPHENO_0000506">
        <rdfs:label>increased filoplume feather length</rdfs:label>
    </owl:Class>

**Comment by nicolevasilevsky** [comment]
these are for some curation I did for Monarch, of organisms from OMIA. @nlwashington can comment further.

**Comment by drseb** [comment]
I am asking because they don't seem to have super or sub-classes in vertebrate.owl and also no equivalence-class axioms...

**Comment by nicolevasilevsky** [comment]
Honestly, I am not very familiar with vertebrate.owl, I just used term genie per @nlwashington's suggestion. @cmungall and @nlwashington- could you comment on this?
Thank you!

**Comment by drseb** [comment]
@mellybelly @cmungall 

are these classes used for annotation somewhere? otherwise I suggest to remove them from vertebrate.owl

**Comment by nlwashington** [comment]
They're used for some bird disease to phenotype curation of OMIA. and really should be properly/logically defined. Would be great to have them.

**Comment by drseb** [comment]
ok thanks! we'll leave the classes there and probably add a comment. closing issue
