### ISSUE TITLE
HP_0000872 Hashimoto thyroiditis and HP_0100646 Thyroiditis have same logical definition

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#173]
HP_0000872 Hashimoto thyroiditis and HP_0100646 Thyroiditis have the same logical definition
'has part' some ('increased rate' and ('inheres in' some ('inflammatory response' and ('part of'     some 'thyroid gland'))) and ('has modifier' some abnormal))

**Hashimoto thyroiditis**
text def: A chronic, autoimmune type of thyroiditis associated with hypothyroidism.

**Thyroiditis**
text def: Inflammation of the thyroid gland.

My thought it is the definition of Hashimoto thyroiditis would be difficult to define with a logical definition, so I recommend removing the logical def.

Related to #149

cc @cmungall @pnrobinson

**Comment by cmungall** [comment]
Is this really a distinct phenotype or a disease?

**Comment by nicolevasilevsky** [comment]
good point, it is a disease in DO: 
DOID:7188 autoimmune thyroiditis (Hashimoto's thyroiditis)

**Comment by nicolevasilevsky** [comment]
Related to #149

**Comment by nicolevasilevsky** [comment]
@pnrobinson what should we do about HP_0000872 Hashimoto thyroiditis?
This is a disease in DO, do we want to keep it in HP?

If yes, I suggest we remove the logical definition.

**Comment by pnrobinson** [comment]
The issue is that some diseases are features of other diseases and it would be difficult to remove this from the HPO database without losing information. We are going to be developing a more generalized way of doing this in the future.

**Comment by cmungall** [comment]
OK, no worries about keeping it in for now

But it's clear the owldef needs to be removed

**Comment by nicolevasilevsky** [comment]
Removed the logical def from HP_0000872 Hashimoto thyroiditis in HPO

**Comment by drseb** [comment]
why not add the modifier "chronic" here? wouldn't that be a better option? @cmungall @pnrobinson

**Comment by cmungall** [comment]
My instinct is no, unless we can be absolutely sure that every instance of a chronic thyroiditis is an instance of HT, and vice versa.

By all means we should add a SubClassOf has-modifier some Chronic. But equivalence seems too strong.

It's hard for me to answer though as I'm having a hard time conceiving of it as a phenotypic feature. I understand the need to keep it in for now, but it seems it may not stay in HP forever. 

If we really do want an equivalence axiom (and I'm not sure we do) it should mirror the text def: A chronic, autoimmune type of thyroiditis associated with hypothyroidism

But are we even sure of the text def? Does it include for example atrophic thyroiditis?
