### ISSUE TITLE
HP_0001913 and HP_0012234 are inferred to be equiv

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#178]
HP_0001913 Granulocytopenia and are inferred to be equiv classes.

**HP_0001913 Granulocytopenia**
Logical def:
'has part' some 
('decreased amount' and ('inheres in' some 
(granulocyte and ('part of' some blood))) and ('has modifier' some abnormal))

**HP_0012234 Agranulocytosis**
Logical def:
'has part' some 
('decreased amount' and ('inheres in' some granulocyte) and ('has modifier' some abnormal))

I am not sure why these are inferred to be equivalent.
Related to #149

@cmungall @pnrobinson

**Comment by nicolevasilevsky** [comment]
@drseb @cmungall @pnrobinson 
Are these are inferred to be equiv because granulocyte is a blood cell? 

There is no explanation in Protege.

**Comment by pnrobinson** [comment]
Agranulocytosis should be "lacks parts", it is not just reduced, it is absent of course.

**Comment by nicolevasilevsky** [comment]
Thanks Peter! I updated the logical def to use 'lacking all parts of type'

**Comment by balhoff** [comment]
I still cannot understand how the two original expressions are equivalent. @cmungall this is a puzzler.

**Comment by balhoff** [comment]
Oh! I see, should have been obvious. Agranulocytosis is asserted to be a subclass of Granulocytopenia. However the definition of Granulocytopenia was a subclass of the definition of Agranulocytosis. Reciprocal subclasses are equivalent.

**Comment by cmungall** [comment]
@nicolevasilevsky do we have a reason to use (granulocyte and ('part of' some blood)) in one and plain granulocyte in the other? We might think a reasoner would infer these two expressions to be equivalent but in fact CL lacks any axiom that restricts granulocytes to blood (presumably as they can be found in lymph too)

**Comment by nicolevasilevsky** [comment]
good point, I will add (granulocyte and ('part of' some blood)) to HP_0012234 Agranulocytosis

**Comment by cmungall** [comment]
But the text says 

*def: "Marked decrease in the number of granulocytes." [HPO:probinson]*

It's always a red flag if the OWL definition starts dropping in extra clauses that are not in the text

**Comment by pnrobinson** [comment]
-penia means simply reduced (like penurious)
-a... means complete lack of
so basically Agranulocytosis is a severe form of Granulocytopenia

I think Nicole already changed the logical definitions and now all seems to be correct. I am closing this issue.
