### ISSUE TITLE
Albinism is inferred to be equiv to Generalized hypopigmentation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#179]
HP_0001022 Albinsim is inferred to be equiv to HP_0007513 Generalized hypopigmentation

**HP_0001022 Albinsim**
Logical def:
'has part' some 
('decreased rate' and ('inheres in' some 
(pigmentation and ('occurs in' some 'multicellular organism'))) and ('has modifier' some abnormal))

text def:
An abnormal reduction in the amount of pigmentation (reduced or absent) of skin, hair and eye (iris and retina).

**HP_0007513 Generalized hypopigmentation**
Logical def:
'has part' some 
('decreased rate' and ('inheres in' some 
(pigmentation and ('occurs in' some 'multicellular organism'))) and ('has modifier' some abnormal) and ('has modifier' some generalized))

No text def

I am not sure why these are inferred to equiv, it seems the reasoner is ignoring the 'generalized' modifier.

Similar issue as #178 
Related to #149 
cc @cmungall @pnrobinson

**Comment by nicolevasilevsky** [comment]
@cmungall and @pnrobinson - see comment above

**Comment by pnrobinson** [comment]
is this a inheres in part of issue?

**Comment by cmungall** [comment]
annoying there is no explanation, need to file protege report

but note that in general these kinds of things are easy to track down

You can tell immediately that the owldef for albinism subsumes the owldef for GH

There is a reciprocal assertion in the ontology

```
    % HP:0007513 ! Generalized hypopigmentation
         % HP:0001022 ! Albinism * 
```

```
A SubClassOf B, B SubClassOf A <-> A EquivalentTo B
```

**Comment by cmungall** [comment]
That is the explanation. As to the solution:

Albinism is a single-child. This is always a bad smell (todo: add soft sparql check for this)

No text def is also bad smell - can do we do a push to ensure everything has text defs?

This site http://www.skindermatologists.com/generalized-hypopigmentation.html includes Hypopituitarism, but this is not a pigmentation phenotype in HPO (which seems OK to me, just pointing out)

Other sources seem to indicate that GH is the phenotype and albinism is the disorder?

But let's just make a decision on the owldefs and move on. I suggest removing a def for albinism, keeping a def for GH, but removing the meaningless 'generalized' modifier

**Comment by pnrobinson** [comment]
The issue is that most descriptions are based on disease diagnoses (e.g., http://www.gpnotebook.co.uk/simplepage.cfm?ID=597295152). I do not believe that the type of generalized hypo pigmentation is identical in all these diseases. We were using the word albinism as a proxy. It would be great to hold a dermatology workshop.

**Comment by nicolevasilevsky** [comment]
Removed logical definition for HP_0001022 albinism, as Chris suggested above.

This was the logical def (just for our records):
'has part' some 
    ('decreased rate'
     and ('inheres in' some 
        (pigmentation
         and ('occurs in' some 'multicellular organism')))
     and ('has modifier' some abnormal))
