### ISSUE TITLE
HP_0000711 Restlessness and HP_0000713 Agitation are inferred to be equiv classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#185]
HP_0000711 Restlessness and HP_0000713 Agitation are inferred to be equiv classes

**HP_0000711 Restlessness**
'has part' some 
    ('increased rate'
     and ('inheres in' some 'agitation behavior')
     and ('has modifier' some abnormal))

no text def

**HP_0000713 Agitation**
Logical def:
'has part' some 
    (quality
     and ('inheres in' some 'agitation behavior')
     and ('has modifier' some abnormal))

no text def

I'm not sure what the best solution is here. 'Agitation behavior' is from NBO.

Related to #149

@cmungall @pnrobinson

**Comment by pnrobinson** [comment]
Agitation can be defined as a severe form of restlessness
MeSH: A feeling of restlessness associated with increased motor activity. This may occur as a manifestation of nervous system drug toxicity or other conditions.
However, restlessness does not necessarily imply motor abnormalities (def: the feeling of being unable to sit still, or feeling as though you're on edge and something is about to or needs to happen).
I will try to find "official" definitions of these two terms, but they are definitely not synonymous.

**Comment by nicolevasilevsky** [comment]
@pnrobinson for now, could we remove the logical def from HP_0000711 Restlessness?

**Comment by pnrobinson** [comment]
Restlessness is not a synonym of agitation and I think the definition is incorrect and should be removed.

**Comment by nicolevasilevsky** [comment]
removed logical def from HP_0000711 Restlessness
