### ISSUE TITLE
HP_0001539 Omphalocele and HP_0010866 Abdominal wall defect are inferred to be equiv classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#186]
HP_0001539 Omphalocele and HP_0010866 Abdominal wall defect are inferred to be equiv classes

**HP_0001539 Omphalocele**
'has part' some 
    ('closure incomplete'
     and ('inheres in' some 'abdominal wall')
     and ('has modifier' some abnormal))

text def
A midline anterior incomplete closure of the abdominal wall in which there is herniation of the abdominal viscera into the base of the abdominal cord.

**HP_0010866 Abdominal wall defect**
Logical def:
'has part' some 
    ('closure incomplete'
     and ('inheres in' some 'abdominal wall')
     and ('has modifier' some abnormal))

text def
An incomplete closure of the abdominal wall.

The text def of omphalocele seems more complicated than the logical def.

Related to #149

@cmungall @pnrobinson

**Comment by nicolevasilevsky** [comment]
I think we should remove the logical def for omphalocele, as it seems more complicated than can be described using a standard pattern.
@pnrobinson @drseb

**Comment by pnrobinson** [comment]
Using this definition
An omphalocele is a type of abdominal wall defect in which the intestines, liver and occasionally other organs remain outside of the abdomen in a sac because of a defect in the development of the muscles of the abdominal wall .
suggests maybe having something like
and
(mislocalized towards some intestines)
might be posible?

**Comment by nicolevasilevsky** [comment]
@pnrobinson I don't know how to write that logical def, this works in Protege, but this does not include mislocalised:

'has part' some 
   ('closure incomplete' 
   and ('inheres in' some 'abdominal wall') 
   and (towards some intestine) 
   and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
What about this suggested revision for HP_0001539 Omphalocele (see #205)? (Maybe this doesn't capture the whole definition properly either though)

'has part' some
(herniated
and ('inheres in' some 'abdominal viscera')
and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
I was thinking of something like this.
Not sure if it is correct.
ELK infers the term to be a subclass of mislocalised

'has part' some 
    ('closure incomplete'
     and ('inheres in' some 'abdominal wall')
     and ('has modifier' some abnormal))
and
(mislocalised and ('inheres in part of' some intestine)
 and ('has modifier' some abnormal)
)

@cmungall  ? @drseb  ?

**Comment by nicolevasilevsky** [comment]
This seems to work (you don't get the wrong inference)

'has part' some
(('closure incomplete'
and ('inheres in' some 'abdominal wall'))
and (mislocalised 
and ('inheres in' some intestine))
and ('has modifier' some abnormal))

Not sure if this is correct though!

**Comment by pnrobinson** [comment]
I think this expressed the meaning of omphalocele (although actually other organs variably can be affected but I think the intestines are characteristic, and so this simplification is justifiable!). This is a nice example!

**Comment by cmungall** [comment]
When you see equivalencies can you post the explanation ("?" in Protege, take a screenshot)? This is a good habit in general.

**Comment by nicolevasilevsky** [comment]
It doesn't show anything:
![image](https://cloud.githubusercontent.com/assets/6722114/25835333/afd8fbfe-3432-11e7-8946-fd68d01ed4cd.png)

**Comment by cmungall** [comment]
(my comment was a delayed post from a few hours ago and addressed the first comment in the ticket)

```
'has part' some
(('closure incomplete'
and ('inheres in' some 'abdominal wall')
and (mislocalised
and ('inheres in' some intestine))
and ('has modifier' some abnormal)))
```

This doesn't mean what you intend it to. It may look somewhat intuitively right, but remember, the order you write the elements of an intersection don't mean anything. If you permute and write the intestine after closure incomplete does it still make sense?

Really, it's better to have no equivalence axiom here. But if we're determined, let us start with a standard DP for hernias. There would be two vars here: thing herniated and thing protruding. Once codified we can do some tests on how the compilation of that DP would affect classification.

**Comment by pnrobinson** [comment]
What do you mean with order? If this is describing an observation, then the order doesnt matter? We are not describing the etiology.

**Comment by cmungall** [comment]
> the order you write the elements of an intersection don't mean anything

`IntersectionOf(A B C) == IntersectionOf(C B A)`

```
'closure incomplete'
and ('inheres in' some 'abdominal wall')
and (mislocalised
and ('inheres in' some intestine))
and ('has modifier' some abnormal)))

==

'closure incomplete'
and ('inheres in' some intestine))
and (mislocalised
and ('inheres in' some 'abdominal wall')
and ('has modifier' some abnormal)))
```

what's mislocalized and what is closed in the above?

> We are not describing the etiology.

Sorry, didn't explain very well. This has nothing to do with etiology, just OWL semantics.

**Comment by cmungall** [comment]
Ah, hold on didn't see the extra parentheses there

**Comment by cmungall** [comment]
OK, @pnrobinson's [proposed def](https://github.com/obophenotype/upheno/issues/186#issuecomment-300039761) avoids the ordering issue. Here it is, with indentation:

```
'has part' some
  ('closure incomplete'
   and ('inheres in' some 'abdominal wall')
   and ('has modifier' some abnormal))
and
  (mislocalised
   and ('inheres in part of' some intestine)
   and ('has modifier' some abnormal))
```

Here there is no ambiguity about what structure 'mislocalised' applies to and which 'closure incomplete' applies to

My comment on ordering applied to the [definition here](https://github.com/obophenotype/upheno/issues/186#issuecomment-300040574):

```
'has part' some
(('closure incomplete'
and ('inheres in' some 'abdominal wall')
and (mislocalised
and ('inheres in' some intestine))
and ('has modifier' some abnormal)))
```

note the different parentheses. Subtle but massively important.

Some take homes here:

 * Protege is not a great environment for entering complex OWL definitions. There is no facility to auto-indent expressions as there is in a programming IDE.
 * We need more disjointness axioms in PATO to catch the kind of errors that go unnoticed here
 * complex OWL definitions are a general bad smell pattern. Subtle mistakes are very hard to catch.
 * We should be editing the OWL in DP templates in any case, not in Protege.
 * Even the correctly indented version has subtle co-reference issues. This may have been what you're getting at with the etiology comment Peter. Example: herniated abdomina plus unrelated intestinal shifting (perhaps rare) would be classified here
 * Keep it simple!!!

**Comment by nicolevasilevsky** [comment]
Thanks for the explanation Chris, that is very helpful! However, in Peter's def, you get an inference of 'mislocalised' as a superclass of 'omphalocele- that's not right, right?

And sounds like you don't want to use these complicated logical definitions anyway, right?

Can we just delete the logical def for omphalocele and close this ticket? :)

**Comment by pnrobinson** [comment]
Well, any of the OWL classes are susceptible to mis-interpretation in the way you state, for instance red eye can be caused by somebody pouring red paint on my face and if that gets recorded in the EHR, then presumably corresponding HPO class would be inferred. We should add the PATO term "externally mislocalized", and then there is little chance of misinterpretation. 
But why delete the def, it seems kinda nice?

**Comment by nicolevasilevsky** [comment]
Aren't we getting the wrong inference with the proposed def though? Mislocalised should not be an inferred superclass, right?

**Comment by cmungall** [comment]
@nicolevasilevsky can you post an explanation?

**Comment by cmungall** [comment]
I'm not sure how it's possible to infer peter's class expression is a subclass of pato:mislocalised

**Comment by nicolevasilevsky** [comment]
![image](https://cloud.githubusercontent.com/assets/6722114/25927673/75a46c54-35ac-11e7-88af-5f38a43ebbe9.png)

**Comment by nicolevasilevsky** [comment]
This explanation does not help clarify anything for me, does it for you, @cmungall?

**Comment by balhoff** [comment]
@nicolevasilevsky `mislocalised` should be "wrapped" by a `has part` restriction, I believe. Currently it's being intersected with the `has part` expression.

**Comment by cmungall** [comment]
yes - parentheses are important! Use @pnrobinson's def

**Comment by nicolevasilevsky** [comment]
but @pnrobinson's def is the one that is causing the incorrect inference:

'has part' some
  ('closure incomplete'
   and ('inheres in' some 'abdominal wall')
   and ('has modifier' some abnormal))
and
  (mislocalised
   and ('inheres in part of' some intestine)
   and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
If I add additional parentheses, this fixes it (but is this correct?) (I bolded the extra parentheses)

'has part' some
  **(**('closure incomplete'
   and ('inheres in' some 'abdominal wall')
   and ('has modifier' some abnormal))
and
  (mislocalised
   and ('inheres in part of' some intestine)
   and ('has modifier' some abnormal))**)**

**Comment by cmungall** [comment]
You're quite right, I had my order of precedence rules wrong. 😧 

https://www.w3.org/TR/owl2-manchester-syntax/#Descriptions
Conjunctions have lower precedence than restriction. I will repeat this 100 times, and tattoo the BNF onto my chest! May the OWL gods forgive me.

**Comment by nicolevasilevsky** [comment]
Haha @cmungall!

**Comment by pnrobinson** [comment]
Of course, so the parens were the reason for mislocalised subclass inference ...

**Comment by nicolevasilevsky** [comment]
@pnrobinson, what do you meant the parents were the reason? Can you explain further?

**Comment by pnrobinson** [comment]
Sorry, I meant the parenTHESES not the parenTS. As Chris pointed out, the definition I originally tried was essentially
has_part some (other stuff) and mislocalised  
i.e.
(has_part some (other stuff)) and mislocalised

**Comment by nicolevasilevsky** [comment]
Ah, thanks for clarifying @pnrobinson!

So, what is the resolution here? Is this logical definition okay to use:
'has part' some
(('closure incomplete'
and ('inheres in' some 'abdominal wall')
and ('has modifier' some abnormal))
and
(mislocalised
and ('inheres in part of' some intestine)
and ('has modifier' some abnormal)))

**Comment by nicolevasilevsky** [comment]
Or do we want to delete the current logical def? Because we still have the incorrect equivalence (as stated above)

**Comment by nicolevasilevsky** [comment]
I added a revised logical def to HP_0001539 Omphalocele, see #205 

Please reopen if the logical definition of should be revised.
