### ISSUE TITLE
HP_0004299 Hernia of the abdominal wall and HP_0010866 Abdominal wall defect are inferred to be equiv classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#187]
HP_0004299 Hernia of the abdominal wall and HP_0010866 Abdominal wall defect are inferred to be equiv classes

**HP_0004299 Hernia of the abdominal wall**
'has part' some 
    (herniated
     and ('inheres in' some 'abdominal wall')
     and ('has modifier' some abnormal))

text def
The presence of a hernia in the abdominal wall.

**HP_0010866 Abdominal wall defect**
Logical def:
'has part' some 
    ('closure incomplete'
     and ('inheres in' some 'abdominal wall')
     and ('has modifier' some abnormal))

text def
An incomplete closure of the abdominal wall.

Not sure why these are inferred to be equiv.

Related to #149

@cmungall @pnrobinson

**Comment by drseb** [comment]
can you try to get the explanation in protege please?

probably related to another ontology

**Comment by nicolevasilevsky** [comment]
I looked for an explanation in Protege, but it did not give me one.

**Comment by nicolevasilevsky** [comment]
not sure what changed here but these are not longer inferred to be equivalent.
