### ISSUE TITLE
HP_0005920 Abnormality of the epiphyses of the phalanges of the hand and HP_0005924 Abnormality of the epiphyses of the hand

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#190]
HP_0005920 Abnormality of the epiphyses of the phalanges of the hand and HP_0005924 Abnormality of the epiphyses of the hand

**HP_0005920 Abnormality of the epiphyses of the phalanges of the hand**
'has part' some 
    (quality
     and ('inheres in' some 'epiphysis of phalanx of manus')
     and ('has modifier' some abnormal))

text def
Abnormality of the epiphyses of the fingers

**HP_0005924 Abnormality of the epiphyses of the hand**
Logical def:
'has part' some 
    (quality
     and ('inheres in' some 
        ('epiphysis of phalanx of manus'
         and ('part of' some 'manual digit')))
     and ('has modifier' some abnormal))

text def
Any abnormality of the epiphyses of the phalanges or metacarpal bones.

Could we revise the logical def for 'Abnormality of the epiphyses of the hand' to include an "or"?
'has part' some 
    (quality
     and ('inheres in' some 
        ('epiphysis of phalanx of manus' or 'epiphysis of metacarpal bone'
         and ('part of' some 'manual digit')))
     and ('has modifier' some abnormal))

Related to #149

@cmungall @pnrobinson

**Comment by cmungall** [comment]
ORs are a bad smell

I think this is fine

epiphysis of the hand == epiphysis and part_of some UBERON:0001442 ! skeleton of manus

This is also UBERON:0012151 ! skeleton of manual digitopodium 

but I don't think necessary

**Comment by nicolevasilevsky** [comment]
Added new logical def to HP_0005924 Abnormality of the epiphyses of the hand:

'has part' some 
    (quality
     and ('inheres in' some 
        (epiphysis and ('part of' some 'skeleton of manus')))
     and ('has modifier' some abnormal))
