### ISSUE TITLE
HP_0010674 Abnormality of the curvature of the vertebral column and HP_0100795 Abnormally straight spine are inferred to be equiv classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#192]
HP_0010674 Abnormality of the curvature of the vertebral column and HP_0100795 Abnormally straight spine are inferred to be equiv classes

**HP_0010674 Abnormality of the curvature of the vertebral column**
'has part' some 
    (curvature
     and ('inheres in part of' some 'vertebral column')
     and ('has modifier' some abnormal))

text def
The presence of an abnormal curvature of the vertebral column.

**HP_0100795 Abnormally straight spine**
'has part' some 
    (straight
     and ('inheres in part of' some 'vertebral column')
     and ('has modifier' some abnormal))

text def
The absence of the normal curvature of the vertebral column.

Could we revise the logical def for Abnormally straight spine to

'has part' some 
    (straight
     and ('inheres in part of' some 'vertebral column')
     and ('has modifier' some abnormal))

Related to #149

@cmungall @pnrobinson

**Comment by drseb** [comment]
I can't see a difference of your suggested revision to the current def. Can you help me see it?

**Comment by nicolevasilevsky** [comment]
My bad, it's fixed now.

**Comment by cmungall** [comment]
Assume a typo and PATO:0002180 ! straight  intended?

**Comment by nicolevasilevsky** [comment]
yep, I meant straight

**Comment by nicolevasilevsky** [comment]
I revised the logical definition for HP_0100795 Abnormally straight spine to 
'has part' some
(straight
and ('inheres in part of' some 'vertebral column')
and ('has modifier' some abnormal))
