### ISSUE TITLE
HP_0002493 Upper motor neuron dysfunction and HP_0007256 Abnormal pyramidal signs are inferred to be equiv classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#193]
HP_0002493 Upper motor neuron dysfunction and HP_0007256 Abnormal pyramidal signs are inferred to be equiv classes

**HP_0002493 Upper motor neuron dysfunction**
'has part' some 
    ('decreased functionality'
     and ('inheres in' some 'corticospinal tract')
     and ('has modifier' some abnormal))

text def
A functional anomaly of the upper motor neuron. The upper motor neurons are neurons of the primary motor cortex which project to the brainstem and spinal chord via the corticonuclear, corticobulbar and corticospinal (pyramidal) tracts. They are involved in control of voluntary movements.
Dysfunction leads to weakness, impairment of fine motor movements, spasticity, hyperreflexia and abnormal pyramidal signs.

**HP_0007256 Abnormal pyramidal signs**
'has part' some 
    ('decreased functionality'
     and ('inheres in' some 'corticospinal tract')
     and ('has modifier' some abnormal))

text def
Functional neurological abnormalities related to dysfunction of the pyramidal tract.

Potential new logical def for 'upper motor neuron dysfunction"
'has part' some 
    ('decreased functionality'
     and ('inheres in' some (neuron and ('part of' some 'primary motor cortex')))
     and ('has modifier' some abnormal))

Related to #149

@cmungall @pnrobinson

**Comment by nicolevasilevsky** [comment]
@drseb @cmungall @balhoff 
Is this logical def okay, is it okay to have 'decreased functionality' with a cell/anatomical entity?

'has part' some
('decreased functionality'
and ('inheres in' some (neuron and ('part of' some 'primary motor cortex')))
and ('has modifier' some abnormal))

**Comment by cmungall** [comment]
if it says it's OK in the yaml

**Comment by nicolevasilevsky** [comment]
Looks like we don't have a yaml pattern for that per se, but I do see that other terms are using decreased functionality with anatomical structures. I will update this logical def for HP_0002493 Upper motor neuron dysfunction and add a yaml pattern too.

**Comment by nicolevasilevsky** [comment]
added revised logical def to HP_0002493 Upper motor neuron dysfunction
'has part' some
('decreased functionality'
and ('inheres in' some (neuron and ('part of' some 'primary motor cortex')))
and ('has modifier' some abnormal))

**Comment by nicolevasilevsky** [comment]
@balhoff I added two new yaml patterns, would you mind checking them?
https://github.com/obophenotype/upheno/blob/master/src/patterns/decreasedFunctionalityInLocation
https://github.com/obophenotype/upheno/blob/master/src/patterns/increasedFunctionalityInLocation

**Comment by balhoff** [comment]
I made a couple of tweaks to the patterns.

**Comment by balhoff** [comment]
@nicolevasilevsky actually there are a few problems. Instead of variable names the pattern is using 'anatomical entity'. I assume you want 'entity' here instead. But you have 2 vars defined so I don't want to jump to conclusions.
