### ISSUE TITLE
Add EqAxioms for "susceptibility to weight loss" and similar terns

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#2]
Originally reported on Google Code with ID 1
```
See:

https://sourceforge.net/tracker/?func=detail&atid=1109502&aid=3587904&
group_id=76834

for explanation. Be sure definition follows this
```

Reported by `cmungall` on 2012-11-16 23:31:28

**Comment by drseb** [comment]
I guess this can be closed. does not seem to be easy to define

ping: @cindyJax  (maybe add to mp-tracker?)
