### ISSUE TITLE
Wiki transfer from google code worked correctly?

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#208]
I have the feeling that transferring the page https://github.com/obophenotype/upheno/wiki/PhenotypeModelCompetencyQuestions did not work properly. Was there more content on that page before the transfer from google code @cmungall ?

**Comment by cmungall** [comment]
Yes, and a few other pages too, e.g. modeling absence. I'm not quite 
sure how to resolve this.

**Comment by drseb** [comment]
If there are no backups, then just close this issue. I don't think it is realistic that we have time to re-write this...
