### ISSUE TITLE
Need yaml template for more complicated logical defs

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#214]
@cmungall 
Could you provide me with an example yaml template for a logical def that uses two vars/entities such as:

'has part' some
(‘having extra processual parts’ and 
('inheres in' some ([**GO process**] and ‘occurs in’ some [**UBERON or GO CC**])) 
and ('has modifier' some abnormal))

MP example:
astrocytosis [MP:0003354]
currently:
'has part' some
(‘having extra processual parts’ and 
('inheres in' some (‘cell proliferation’ and ‘occurs in’ some astrocyte)) 
and ('has modifier' some abnormal))

**Comment by cmungall** [comment]
@dosumis has lots of examples

https://github.com/dosumis/dead_simple_owl_design_patterns/tree/master/patterns

E.g. https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/patterns/import_across_membrane.yaml

**Comment by nicolevasilevsky** [comment]
excellent, thanks! I'll take a look.
