### ISSUE TITLE
how to model 'missing process'?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#216]
Old ticket from [google code](https://code.google.com/archive/p/phenotype-ontologies/issues/109)

I am unsure of the pattern we want to use for 'missing process' Please refer to that section in this doc: https://docs.google.com/document/d/1LOYQ6pOlvapzJhHbSA_Rb3aZYylXZ564B78jiysvB-U/edit#heading=h.cndwdf5tinuu

Should the structure be: structure: has part' some (absent and (‘inheres in’ some 'process) and (‘has modifier’ some abnormal))

There are still some cases in MP/HP that are using 'lacking processual parts', should these be updated?

**Comment by nicolevasilevsky** [comment]
see https://github.com/obophenotype/upheno/blob/master/src/patterns/missingProcess.yaml

**Comment by drseb** [comment]
lacks processual parts ? is it in pato?

**Comment by nicolevasilevsky** [comment]
lacking processual parts is in patp

**Comment by drseb** [comment]
is this the answer to your question?

**Comment by nicolevasilevsky** [comment]
@cindyJax  commented on the [Berlin doc](https://docs.google.com/document/d/10NCd9jXGXA4BETSBxdbVGfDFM2w4gAIbY6vpm4ERTBo/edit#) that we had never decided on whether to use of 'absent'  or 'lacking processual parts' with processes. She noted in PATO, 'absent' remains a 'physical object quality' rather than a 'process quality', so at the Portland meeting we decided it best to use ‘lacks processual parts’ in these cases.

I created this yaml pattern here: https://github.com/obophenotype/upheno/blob/master/src/patterns/missingProcess.yaml

**Comment by drseb** [comment]
ah wait - I see. Let's see what is used more often!

**Comment by nicolevasilevsky** [comment]
ok - will you check? :)

**Comment by drseb** [comment]
no. no need to. @cindyJax is right. if the phenotype is referring to processes, we have to use a quality from the "process quality" subontology in PATO
