### ISSUE TITLE
abnormal level pattern

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#220]
@nicolevasilevsky 

I think this pattern should make use of chebi and name abnormalLevelOfChemical.yaml (right now it uses owl:thing)

Do you agree?

Do we have abnormal level of other entities as well? Like uberon?

**Comment by nicolevasilevsky** [comment]
@drseb I updated that [pattern](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfChemical.yaml) to be more specific for chemical levels

Yes, we do have abnormal levels of chemical entities in anatomical structures/cells, like:
Abnormal muscle fiber protein expression
Looks like the pattern is:
'has part' some 
(amount and ('inheres in' some 
(protein and ('part of' some 'cell of skeletal muscle'))) and ('has modifier' some abnormal))

I can create a yaml file for this pattern too

**Comment by nicolevasilevsky** [comment]
I created another pattern for [abnormal Level Of Chemical In Entity](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfChemicalInEntity)

**Comment by balhoff** [comment]
@nicolevasilevsky I forgot to tell you that I updated my DOSDP to handle prefixes better. So you should use CURIEs in all the ID references in these patterns. I updated the previous patterns.

**Comment by nicolevasilevsky** [comment]
Thanks @balhoff! I updated a couple of the files, let me know if there are any issues.

**Comment by nicolevasilevsky** [comment]
I think this can be closed, please reopen if not.
