### ISSUE TITLE
question about yaml pattern

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#223]
https://github.com/obophenotype/upheno/blob/master/src/patterns/missingProcess.yaml

Some of these patterns have the has_part relation listed twice, is that necessary or can I delete the second has_part?

![image](https://cloud.githubusercontent.com/assets/6722114/25412627/014e9610-29d9-11e7-99ed-9c632a8fa7c5.png)

**Comment by balhoff** [comment]
It's redundant. You just need to define the mapping once.

**Comment by nicolevasilevsky** [comment]
Thanks @balhoff. Not sure how that got introduced, but I went through and (hopefully) removed all the redundant occurrences of has_part: BFO:0000051.
