### ISSUE TITLE
Question about midface retrusion and midface hypoplasia

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#227]
MP has two terms for midface retrusion (MP_0009855) and midface hypoplasia (MP_0012085), whereas HP has midface retrusion (HP_0011800) and midface hypoplasia is a synonym.

Should these terms be consistent in both ontologies?

@cmungall @mellybelly @markengelstad @pnrobinson @sbello @cindyJax

**Comment by markengelstad** [comment]
Yes, I agree --  they are synonyms, and should be consistent across MP and HP. 

Let me know if you want to set aside a few hours to go over all of the overlapping terms involved in facial growth/ facial phenotypes.  I'll join you!

**Comment by sbello** [comment]
Is it always the case that retrusion = underdevelopment? And do all forms of midface hypoplasia result in retrusion?

Looking at the definition of retrusion (http://medical-dictionary.thefreedictionary.com/retrusion) online, it is defined as "the state of being located posterior to the normal position, such as the mandible or a tooth displaced in the line of occlusion." So it would seem that you could have retrusion without being hypoplastic/underdeveloped. Looking at the only paper annotated to MP:0009855 it seems like this could easily be moved to MP:0012085 as the skulls in this case really look underdeveloped.
Looking at https://elementsofmorphology.nih.gov/index.cgi?tid=5b7ad34ab35682b5 it appears that midface retrusion replaces midface hypoplasia but I think I would need to dig into this more to make sure all types of midface hypoplasia = midface retrusion.

**Comment by pnrobinson** [comment]
See this discussion of midface retrusion in humans

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2778021/

This is what the HPO term is based on.

**Comment by markengelstad** [comment]
Sue, I know what you are saying and one could spin in circles on these terms and their usage..  

Most midface 'retrusion' or 'hypoplasia' is really a comment on the midface relation to the mandible. 
A clinician looks at the jaws, sees that they aren't harmonious, then decides which one (or both) is the one that grew too much or too little, then labels that jaw with a finding like hypoplasia or retrusion.  These labels are confusing and arbitrary.  For instance, no one uses 'mandibular retrusion', but why not?  And how do we know, which jaw really did or didn't grow 'correctly'?  Usually, All we really know is that one is bigger than the other. 

Really, there are two kinds of midface underdevelopment, and they are unfortunately used interchangeably by clinicians: 
1: the midface is small compared to the mandible, but its actual size (based on cephalometric measurements /relation to the skull base) is normal. 
2: the midface is intrinsically small based on its cephalometric measurements /relation to the skull base.

I find the terms created by the Elements of Morphology paper, especially in regard to the midface, to be too vague and arbitrary, but that's what we have to work with, I guess.

**Comment by mellybelly** [comment]
nah, make it so in HPO and maybe in 5 yrs people will be more specific ;-)

**Comment by sbello** [comment]
Six years later and I've finally made a change in the MP for this, obsolete midface retrusion and made this a synonym for midface hypoplasia. From what I could find midface retrusion seems to be used primarily for the human phenotype with midface hypoplasia then used for mouse or other models
