### ISSUE TITLE
pr_import fails

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#228]
calling `make imports/pr_import.owl` produces an empty ontology. 

The makefile told me that it was missing `obo-grep.pl`. (not sure why this is need, as we want the owl-version!?)

I downloaded it from https://raw.githubusercontent.com/cmungall/obo-scripts/master/obo-grep.pl

Do you have an idea what is wrong? Does it work for you?

**Comment by drseb** [comment]
I am having problems to point the makefile to my `obo-grep.pl`. Can you help? Can we add `obo-grep.pl` to the upheno-dir and hardcode the path to it in the makefile?

**Comment by drseb** [comment]
ping @cmungall

**Comment by cmungall** [comment]
oh dear, this is a bit of an old makefile. We should tidy this up and start using robot. Is it OK if I add a robot dependency for this one?

If you need a quick fix, get the script here, but this is the path of evil...
https://github.com/cmungall/obo-scripts/

**Comment by drseb** [comment]
See my initial question. I already grabbed it from `obo-scripts`. I could manage to run it, but this is all kind of horrible... (see my next issue)

I will close this one
