### ISSUE TITLE
Re-generation of imports leads to build errors

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#229]
Hi,

with the re-run of make imports/xxx.owl, we are now having issues with **logic inconsistencies**. See e.g. https://travis-ci.org/obophenotype/human-phenotype-ontology/jobs/232460614 or http://build.berkeleybop.org/job/build-hp-edit/1946/console

This comes from one of the re-mireoted ontologies, i.e. chebi or uberon or GO. 

Any ideas how to quickly fix this @cmungall ?

**Comment by cmungall** [comment]
The most common cause of this is two separate uberon imports in the chain, each coming from different versions. Need a quicker way to analyze these than looking in Protege..

@nicolevasilevsky can you take a look and generate an explanation, and see if the axioms are coming from 2 places?

**Comment by drseb** [comment]
![screen shot 2017-05-15 at 19 18 08](https://cloud.githubusercontent.com/assets/5172897/26070022/521bc1a6-39a3-11e7-8ebd-50ba8abf3d18.png)

@cmungall Why are there disjointness axioms in uberon? I thought we remove them for the import purpose?

**Comment by cmungall** [comment]
They're there for detecting errors. I don't recall removing them in
imports.

**Comment by cmungall** [comment]
Related ticket: https://github.com/obophenotype/uberon/issues/1189

It looks like there is a very stale set of uberon axioms kicking around in the import chain, conj-sac hasn't been part of the eyeball since 2015:
https://github.com/obophenotype/uberon/commit/914304d75a48ed17a9edb175be36bbc60f9666f2

**Comment by drseb** [comment]
fixed
