### ISSUE TITLE
errors in OMIM:270220 annotation

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#23]
Originally reported on Google Code with ID 22
```
The disease OMIM:270220 is entitled, 
"SJOGREN-LARSSON-LIKE ICHTHYOSIS WITHOUT CNS OR EYE INVOLVEMENT" 
http://omim.org/entry/270220

but, it has an annotation to "abnormality of the eye".  

i think this is incorrect.



```

Reported by `nicole.l.washington` on 2014-05-13 20:09:01

**Comment by drseb** [comment]
thanks @nlwashington !! 

converted them to negative annotations. see https://github.com/monarch-initiative/hpo-annotation-data/commit/3ef67738c551a7fbbc8e41cfacc61d9d94dd4590
