### ISSUE TITLE
add terms to the UBERON import

### ISSUE THREAD

**Issue by sbello** [obophenotype/upheno#237]
I've added 3 terms to the UBERON import
 http://purl.obolibrary.org/obo/UBERON_0001627 (middle cerebral artery)
 http://purl.obolibrary.org/obo/UBERON_0001624 (anterior cerebral artery)
 http://purl.obolibrary.org/obo/UBERON_0001636 (posterior cerebral artery)

We need to run the process to regenerate the imports.

Thanks, 
Sue

**Comment by cmungall** [comment]
Currently we're configured such that the imports are driven from what's 
in mp-edit.owl, and I don't see UBERON_0001627 in the mp-edit from 
github.

We can change this pipeline any time so it's driven by an explicit file 
of term IDs

(btw am in BH, at Oceanside, not sure if you are around for any of the 
PRO meeting)

**Comment by sbello** [comment]
Hi Chris
The commit is pending

**Comment by drseb** [comment]
@cmungall we have switched to using the explicit file some months ago. maybe we should chat before you change something. right now we have only me (and probably you) as persons that know how to generate the import-files
