### ISSUE TITLE
inconsistentOntologyException 

### ISSUE THREAD

**Issue by tkonopka** [obophenotype/upheno#243]
I am running owltools and getting an InconsitentOntologyException. I've traced the error to the upheno/imports/ro_import.owl file. This file has more than doubled in size in the last week. My owltools command runs normally using ro_import.owl from last week (downloaded 2017/10/15), but throws the exception when using the file from today (2017/10/23).

I see changes to this file in past week. Please advise on status?

**Comment by drseb** [comment]
What exactly are you running in owltools, i.e. what Ontology is inconsistent now?

We also had some issues after updating ro_import (see https://github.com/obophenotype/human-phenotype-ontology/pull/2614).

**Comment by drseb** [comment]
Discussed via email. Closing for now (otherwise I'll forget to close). This depends on a few logical definitions that have to be repaired in MP (reported to MP via email).
