### ISSUE TITLE
NCIT_C3263/NCIT_C3431 in hp.owl

### ISSUE THREAD

**Issue by RLWOHIO** [obophenotype/upheno#244]
Not sure this is the right place for hp.owl issues. 
Current, hp.owl contains:

<rdf:Description rdf:about="http://purl.obolibrary.org/obo/NCIT_C3263">
    <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/NCIT_C3431"/>
</rdf:Description>

Yet in mpath_import.owl:

<owl:Class rdf:about="http://purl.obolibrary.org/obo/NCIT_C3431">
    <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/NCIT_C3263"/>
 ...
I believe the statement in hp.owl is erroneous.  And it fails vertebrate.owl.  I tried to take care of it locally by commenting it out, but somehow caused a series of other problems.  As a result, I am unable to assemble the ontologies and reason.  Jim Balhoff posted this issue somewhere a few weeks ago and it is yet to be addressed.

Thanks for your attention on this matter,

Ronglin Wang

**Comment by drseb** [comment]
Thanks for reporting. Is already fixed (https://github.com/obophenotype/human-phenotype-ontology/issues/2594) and will be visible when I make the new release in a few days.
