### ISSUE TITLE
Help with updating ro_import.owl

### ISSUE THREAD

**Issue by balhoff** [obophenotype/upheno#247]
Hi @drseb @cmungall I tried adding a [term](http://purl.obolibrary.org/obo/RO_0002296) to imports_requests.owl in support of https://github.com/obophenotype/mammalian-phenotype-ontology/pull/2529, but when I run `make imports/ro_import.owl`, this property is added as a bare annotated IRI without an ObjectProperty declaration. Any ideas?

**Comment by drseb** [comment]
The current strategy is to add the RO class to import_requests.owl. Then push the changed import_requests file. Then run your make command. Does that make a difference for you?

**Comment by balhoff** [comment]
Here is how I added it:

https://github.com/obophenotype/upheno/commit/9d5323796a1787c11b3506d058698b908c699f5e

I can't really understand what's happening—the term seems to be added to ro_import but it is not declared as an ObjectProperty. It looks like this:

```xml
    <!-- 
    ///////////////////////////////////////////////////////////////////////////////////////
    //
    // Annotations
    //
    ///////////////////////////////////////////////////////////////////////////////////////
     -->

    <rdf:Description rdf:about="http://purl.obolibrary.org/obo/RO_0002296">
        <rdfs:label xml:lang="en">results in development of</rdfs:label>
        <obo:IAO_0000117>Chris Mungall</obo:IAO_0000117>
        <obo:IAO_0000112 xml:lang="en">every flower development (GO:0009908) results in development of some flower (PO:0009046)</obo:IAO_0000112>
        <obo:IAO_0000115>p &apos;results in development of&apos; c if and only if p is a developmental process and p results in the state of c changing from its initial state as a primordium or anlage through its mature state and to its final state.</obo:IAO_0000115>
        <oboInOwl:shorthand rdf:datatype="http://www.w3.org/2001/XMLSchema#string">results_in_development_of</oboInOwl:shorthand>
        <obo:IAO_0000119 rdf:datatype="http://www.w3.org/2001/XMLSchema#anyURI">http://www.geneontology.org/GO.doc.development.shtml</obo:IAO_0000119>
        <obo:IAO_0000114 rdf:resource="http://purl.obolibrary.org/obo/IAO_0000125"/>
    </rdf:Description>
    
```

**Comment by balhoff** [comment]
This was made obsolete by #250.
