### ISSUE TITLE
zp.owl and zebrafish genes annotated by zp terms

### ISSUE THREAD

**Issue by RLWOHIO** [obophenotype/upheno#249]
http://compbio.charite.de/jenkins/job/zp-owl/annot_gene_pos.txt was built two years ago.  It contains about 2800 genes.  Does it have a more up to date version?  In comparison, Zfin_phenoGeneCleanData_fish.txt in Zfin had about 5900 genes as of September this year.  Thanks.
--

**Comment by drseb** [comment]
http://compbio.charite.de/jenkins/job/zp-owl-new/
