### ISSUE TITLE
pattern for using multiple PATO terms?

### ISSUE THREAD

**Issue by sbello** [obophenotype/upheno#251]
Is there a way to use more than one PATO term in a logical definition? For example we have the MP term 'plush coat' defined as 'coat has a thick, velvet-like appearance' I think I could define this using both the PATO term 'increased thickness' and the term 'soft' but I'm unsure how or if this would work in the standard patterns. All the other terms have a single PATO term preceding the entity being described.
Thanks,
Sue

**Comment by cmungall** [comment]
In this case I think plush is a perfectly lovely PATO term. PATO could have axioms that state that this quality is composed of a softness aspect and an increased thickness (using has-part). This has some pragmatic advantages in that if we want to compare with a cat or otter ontology we don't have to rely on picking the same pair of PATO terms.

If we did was to post coordinate I'd just taken an expression like

`has-part some (Q and inheres-in some E)`

and replace the `Q` with `(quality and has-part some Q1 and has-part some Q2)`

possibly adding more sub-qualities.

obviously you have to watch your parentheses and make sure the nesting is happening at the right level - another reason to pre-coordinate.

All this is consistent with the BFO guide, where quality partonomies are encouraged.

**Comment by sbello** [comment]
Thanks! I'll submit a request to PATO for a new term.

**Comment by sbello** [comment]
PATO ticket https://github.com/pato-ontology/pato/issues/142

**Comment by matentzn** [comment]
@sbello Can this be closed?

**Comment by sbello** [comment]
Sure
