### ISSUE TITLE
Current versions of mp-hp mappings are outdated.

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#255]
The Mouse group at EBI approached me because they urgently need an updated version of http://purl.obolibrary.org/obo/upheno/mp-hp-view.owl. Ideally, they would like to maintain and trigger the mapping themselves whenever they need it (for example whenever MP or HP change), if it is easy to do. They want a response by next Friday, I think they will move away from mp-hp-view otherwise... At the moment the pipeline using the makefile does not execute, presumably because of some broken definitions in MP.

**Comment by matentzn** [comment]
If there is anything that I can help with, like reviewing changes, testing the pipeline or seducing the Mouse people into giving us a bit more time, let me know.

**Comment by balhoff** [comment]
I'm now able to run the target `mp-hp-view.owl` without error. Do they need an official release? I don't know the exact procedure for that.

**Comment by matentzn** [comment]
Jim, thanks a ton.. Indeed, it looks like it might be working now! :) I will look whether everything was done correctly, and close the issue next week.

**Comment by matentzn** [comment]
And I wouldn't worry about the official release at the moment. They would like to be able to generate upheno related mappings by themselves, on demand, anyway.

**Comment by matentzn** [comment]
As far as I understand at the moment, the Mous folks should be happy with the file. Closing this.
