### ISSUE TITLE
Invalid use of "part of" characteristics make reasoning behaviour unspecified.

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#256]
The Human phenotype ontology, as currently located at http://purl.obolibrary.org/obo/hp.owl, is dependent on a upheno import (http://purl.obolibrary.org/obo/upheno/imports/go_import.owl) which is not in OWL 2 DL. As far as I can see, the reason for that is a violation of a global constraint, (irregular role hierarchy):

`Use of non-simple property in functional axiom <http://purl.obolibrary.org/obo/BFO_0000050> [FunctionalObjectProperty(<http://purl.obolibrary.org/obo/BFO_0000050>) in OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/upheno/imports/go_import.owl>) VersionIRI(<null>))]
`

On closer look, it seems that 'part of' (the relation causing the problem), is specified as both transitive and functional. Taking a look at RO, 'part of' is merely transitive. I think this should be fixed asap, as complete reasoning is otherwise not possible (in fact, HermiT refuses to even try classifying HP).

**Comment by matentzn** [comment]
The same goes for Mammalian Phenotype Ontology.

**Comment by balhoff** [comment]
This was an accident in GO and fixed a while back: https://github.com/geneontology/go-ontology/pull/14295

So `go_import.owl` needs to be refreshed. Clearly we need to make a practice of updating these modules much more frequently!

**Comment by matentzn** [comment]
Can we nudge anyone to do it? :) If it is just about running all targets in the upheno makefile I would even do it.. Unless the file needs changing of course.
