### ISSUE TITLE
go_import.owl misclassifies UBERON_0000000 [anatomy] as BFO_0000003 [occurrent]

### ISSUE THREAD

**Issue by jimmccusker** [obophenotype/upheno#264]
This leaves importing ontologies with significant inconsistencies. It should be mapped as BFO_0000002 [continuant].

**Comment by balhoff** [comment]
Hi @jimmccusker, UBERON:0000000 is [processual entity](http://purl.obolibrary.org/obo/UBERON_0000000), which subsumes 'life cycle' and 'life cycle stage'. These should be occurrents. Where do you see inconsistencies arising? Thanks!

Aside: `go_import.owl` does have some stale Uberon stuff and needs to be refreshed. This can cause some incompatibility with the current Uberon; not sure whether that is causing any of your trouble.

**Comment by jimmccusker** [comment]
Then that's the problem. uberon_import.owl seems to think that UBERON:0000000 is anatomy. Somehow the IDs have been mixed up. I'm not sure if the doid_imports set is different from this project, but this whole thing seems to be a bit tangled.

<img width="1014" alt="screen shot 2018-05-08 at 3 29 51 pm" src="https://user-images.githubusercontent.com/602385/39778609-c99689b4-52d4-11e8-9a15-f837966283e9.png">

**Comment by balhoff** [comment]
Oh, I see you're looking at DOID's Uberon extract. That's independent of the piece of Uberon used here, although it should all be consistent. I don't understand where DO got their Uberon extract, it is inconsistent with Uberon itself. I opened a ticket: https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/497

**Comment by jimmccusker** [comment]
I've filed one too, and switched over to do-simple (which they don't have a purl for, natch). Not upheno's fault, closing.

**Comment by balhoff** [comment]
Thanks for catching this!
