### ISSUE TITLE
Proposal: do not overload is-a, use existential restrictions in phenotype ontologies

### ISSUE THREAD

**Issue by cmungall** [obophenotype/upheno#285]
Note this would be a major change for existing ontologies, the purpose of this ticket is to centralize initial discussions and not to actually push a proposal through.

Background: many existing phenotype ontologies are is-a overloaded. This results in problems when using Q-in-E families of patterns, which necessitated the buffer relation has-part-Q-in-E.

The proposal is to use is-a (SubClassOf between two named classes) in a more restricted way. Roughly: the PATO genus class would remain consistent in any one is-a branch (or would reflect pato is-as), same with entities. Other relationship types would be used for cases that do not fix this.

Examples of ontologies that do this: TO, OBA (both use part-of).

E.g. `abnormal tooth morphology SubClassOf part-of some abnormal mouth morphology` (see #277 for how this could be inferred from AOs)

A causal relation may also be appropriate. E.g. `'abnormal tooth development' SubClassOf 'has effect on' some 'abnormal tooth morphology'`

**Comment by cmungall** [comment]
**UPHENO VARIANT**

A less disruptive variant of this is to implement this in a pan-species grouping ontology (ie a upheno with more classes than the existing Q-neutral groupings). This grouping ontology would not employ the has-part buffer, but could still drive inference in the is-a overloaded ssPOs

**Comment by cmungall** [comment]
I found some slides from 2015 that illustrate how this might work particularly in the context of GO->Uberon:

https://docs.google.com/presentation/d/12Dto4SaNNAlxLMg1lVRMB4ImnjYKvLUuDl50iqNRBUk/edit?usp=sharing

**Comment by matentzn** [comment]
This is pretty cool. I will take a closer look after ICBO.

**Comment by cmungall** [comment]
Repo to go with it: https://github.com/cmungall/cpn

**Comment by cmungall** [comment]
Superseded by #291
