### ISSUE TITLE
abscess pattern

### ISSUE THREAD

**Issue by sbello** [obophenotype/upheno#292]
The abscess.yaml uses the PATO term quality (PATO:0000470) however the the MP logical definitions use the PATO term 'increased amount' (PATO:0000470, see for example liver abscess MP:0003332 and tooth abscess MP:0030462). In addition, other abnormal pathology patterns (aneurysm.yaml, abnormalPathology.yaml) use 'increased amount'. I think we should abscess pattern to 'increased amount' to be consistent.

**Comment by nicolevasilevsky** [comment]
@sbello that was just a typo on my end, the label said quality but the ID was for increased amount, I updated the pattern. Thanks for catching that.
