### ISSUE TITLE
Tidy up OWL version of HPO

### ISSUE THREAD

**Issue by cmungall** [obophenotype/upheno#308]
This has various issues such as imported classes floating to the root. I can add some robot commands to the pipeline but not yet...

in the interim I asked Simon to load hp.obo into OLS rather than hp.owl, is that OK with folks? I think it will look cleaner

**Comment by matentzn** [comment]
Okay, Simon Jupp is willing to fix OLS for us and has even found resources to do it. Can we stall this issue until mid-February to see whether we can get a solution that makes us all happy?

**Comment by matentzn** [comment]
We just had a meeting at EBI regarding the new display and Simon has assigned the task to his new developer. Development will start next week. The OLS view will be nice and tidy by end of February. :) . I would like though to understand from @cmungall, what do you mean by 'tidy up' other than fixing the view in OLS? We can't really clean up the view in Protege, as @drseb says; If OLS looks tidy, is this ticket addressed?

**Comment by cmungall** [comment]
I think we still need to tidy here, if there are floaters it's a sign
something is up, e.g log def references obsolete class

**Comment by matentzn** [comment]
Ok I will take a look and generate some suggestions to clean up. If there is any great urgency feel free to ping me, else I will fold this into the general migration to the new ODK.

**Comment by drseb** [comment]
@matentzn @cmungall if it is only a matter of re-generating any `XXX_import.owl` let me know. There might be some old versions hanging around. We can also skype today if you want. I just don't see at the moment where the dangling classes come from.

**Comment by matentzn** [comment]
This is done.
