### ISSUE TITLE
Usage of BFO in uPheno patterns prevents pattern matching

### ISSUE THREAD

**Issue by drseb** [obophenotype/upheno#315]
Maybe discuss in one of our next calls:

https://github.com/obophenotype/upheno/blob/0a3203f9dc3b98c5988ba742e284c2148ec9a1be/src/patterns/decreasedSize.yaml#L7

@matentzn @cmungall @dosumis

**Comment by matentzn** [comment]
I would like to mention that, replacing bfo:entity with owl:thing in all the patterns, gives a much better picture of pattern coverage:

![image](https://user-images.githubusercontent.com/7070631/52057685-95632600-255d-11e9-83bd-4c4bc5ff4c9e.png)

**Comment by matentzn** [comment]
This issue has become very low priority as we have workarounds in place as part of the new uPheno pipeline. Closing for now!
