### ISSUE TITLE
Review: abnormalMorphologyInLocation

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#317]
[abnormalMorphologyInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalMorphologyInLocation.yaml)

I am confused about the 'position' class declaration:
```
classes:
  position: PATO:0000140
```

I don't see this mentioned anywhere else in the pattern.

Sofia

**Comment by matentzn** [comment]
Good catch! Will fix this.

**Comment by matentzn** [comment]
Please leave this ticket open until the review of the above pattern is completed by 5 or more editors.

**Comment by ybradford** [comment]
this should probably also be limited to anatomical structures (entity is BFO:0000001)

**Comment by nicolevasilevsky** [comment]
pattern_name: abnormalMorphologyOfAnatomicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalMorphologyOfAnatomicalEntityInLocation.yaml
description: ""

classes:
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  morphology: PATO:0000051

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

annotationProperties:
  exact_synonym: oio:hasExactSynonym

vars:
  anatomical_entity: "'anatomical entity'"
  location: "'anatomical entity'"

name:
  text: "morphological abnormality of the %s in the %s"
  vars:
   - anatomical_entity
   - location

annotations:
  - annotationProperty: exact_synonym
    text: "Abnormal %s in the %s"
    vars:
     - anatomical_entity
     - location

def:
  text: "A morphological abnormality of the %s in the %s."
  vars:
    - anatomical_entity
    - location

equivalentTo:
  text: "'has_part' some (morphology and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some abnormal))"
  vars:
    - anatomical_entity
    - location

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by chris-grove** [comment]
Can we change the exact synonym to "Abnormal morphology of %s in the %s"? I don't think "Abnormal %s in the %s" is sufficiently specific

**Comment by matentzn** [comment]
Comments consolidated in http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalMorphologyOfAnatomicalEntityInLocation.yaml closing for now
