### ISSUE TITLE
Review: increasedFunctionalityInLocation

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#325]
[increasedFunctionalityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/increasedFunctionalityInLocation.yaml)

See issue #323 
Same issue here. 'entity' is used in the classes definition and in vars definition but not in the equivalentTo statement.

```
classes:
  increased functionality: PATO:0001625
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  entity: BFO:0000001

...

vars:
  anatomical_entity: "'anatomical entity'"
  entity: "'entity'"

...

equivalentTo:
  text: "'has_part' some ('increased functionality' and ('inheres_in' some %s)) and  ('qualifier' some 'abnormal')"
  vars:
    - anatomical_entity
```

**Comment by nicolevasilevsky** [comment]
pattern_name: increasedFunctionalityOfAnatomicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedFunctionalityOfAnatomicalEntityInLocation.yaml
description: ""

classes:
  increased functionality: PATO:0001625
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  entity: BFO:0000001

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

vars:
  anatomical_entity: "'anatomical entity'"
  entity: "'entity'"

name:
  text: "%s dysfunction"
  vars:
   - anatomical_entity

def:
  text: "A functional abnormality of the %s."
  vars:
   - anatomical_entity

equivalentTo:
  text: "'has_part' some ('increased functionality' and ('inheres_in' some %s)) and  ('has_modifier' some 'abnormal')"
  vars:
    - anatomical_entity
 

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by matentzn** [comment]
Consolidated, closing https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedFunctionalityOfAnatomicalEntityInLocation.yaml
