### ISSUE TITLE
Review: abnormalLevelOfMolecularEntity.yaml

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#327]
[abnormalLevelOfMolecularEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/decreasedLevelOfChemicalEntityInLocation.yaml)

We could revise this to be abnormalLevelOfChemicalEntity.yaml, as CHEBI_24431 chemical entity is a parent of CHEBI_23367 'molecular entity', and therefore it would be inclusive or more classes.

Suggested revision below:

pattern_name: abnormalLevelOfMolecularEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns/abnormalLevelOfMolecularEntity

classes:
  amount: PATO:0000070
  abnormal: PATO:0000460
  chemical entity: CHEBI:24431

relations: 
  inheres_in: RO:0000052
  qualifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  chemical_entity: "'chemical entity'"
 
name:
  text: "abnormal level of %s"
  vars:
   - chemical_entity

def:
  text: "An anomaly in the level of %s."
  vars:
    - chemical_entity

equivalentTo:
  text: "'has_part' some ('amount' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
  vars:
    - chemical_entity

**Comment by nicolevasilevsky** [comment]
we could revise [abnormalLevelOfMolecularEntityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfMolecularEntityInLocation.yaml) and the [increased](https://github.com/obophenotype/upheno/blob/master/src/patterns/increasedLevelOfMolecularEntityInLocation.yaml) and [decreased](https://github.com/obophenotype/upheno/blob/master/src/patterns/decreasedLevelOfMolecularEntityInLocation.yaml) patterns too.

**Comment by nicolevasilevsky** [comment]
The [decreasedLevelOfMolecularEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/decreasedLevelOfMolecularEntity.yaml) pattern is the same as the [decreasedLevel.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/decreasedLevel.yaml) pattern, except the former uses molecular entity and the latter uses entity. I don't think we need both of these.

**Comment by mah11** [comment]
> We could revise this to be abnormalLevelOfChemicalEntity.yaml, as CHEBI_24431 chemical entity is a parent of CHEBI_23367 'molecular entity', and therefore it would be inclusive or more classes.

I like this idea, because we have plenty of fission yeast phenotypes (FYPO) with altered levels of ions, especially Ca2+.

**Comment by sbello** [comment]
Second the switch to chemical entity. The MP also has a number of mineral level terms that are using this pattern.

I did a quick search through the MP and I don't see any abnormal level terms with definitions that would not fit the chemical entity pattern. We do have one term 'elevated level of mitotic sister chromatid exchange' that uses 'level' but I think this would fit an enhanced process pattern better. So, I have no objection to dropping DecreasedLevel pattern.

**Comment by matentzn** [comment]
Note also: 

https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfChemical.yaml
https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfMolecularEntity.yaml

Both seem to be restricted by chebi terms.. Do we really need both?

**Comment by nicolevasilevsky** [comment]
@matentzn, no, I don't think we need both those patterns above, I think we should delete [abnormalLevelOfMolecularEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfMolecularEntity.yaml)

- For [abnormalLevelOfMolecularEntityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abnormalLevelOfMolecularEntityInLocation.yaml), we should change molecular entity to chemical entity, then it will be more inclusive

I think we should do the same for these below (change molecular entity to chemical entity):

- decreasedLevelOfMolecularEntity.yaml
- decreasedLevelOfMolecularEntityInLocation.yaml
- increasedLevelOfMolecularEntity.yaml
- increasedLevelOfMolecularEntityInLocation.yaml

**Comment by nicolevasilevsky** [comment]
@mah11 and @sbello, would you mind checking these off on our [uPheno progress](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367) spreadsheet?

**Comment by sbello** [comment]
Note on the spreadsheet there is an HP term that uses decreasedLevel (HP_0005403 'Decrease in T cell count') that would not fit the chemical entity pattern. The MP term 'decreased T cell number' also uses the pattern for the EQ axiom but neither term uses 'level' in the term name. We may want to rename this pattern and rework it match the decreased number/count pattern.
Working on updating the spreadsheet.

**Comment by mah11** [comment]
I would also find it useful to distinguish 'abnormal/increased/decreased amount of a chemical entity' from 'abnormal/etc. number of anatomical (including cell and subcellular) structure(s)'. We have use cases for both in FYPO, so let me know if it would be useful to plug examples in somewhere.

**Comment by mah11** [comment]
I've slipped down a bit of a rabbit hole and checked off several that look consistent with the way FYPO dos or would use them ...

**Comment by srobb1** [comment]
I added contributors and the description and examples from the spreadsheet. Does it look alright?

https://github.com/obophenotype/upheno/pull/368

**Comment by ybradford** [comment]
in the spreadsheet this [decreasedLevelOfChemicalEntityInLocation.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/decreasedLevelOfChemicalEntityInLocation.yaml) is linked to this ticket. Th decreasedLevelOfChemicalEntityInLocation still lists 'Molecular Entity' but should be 'Chemical Entity'.

**Comment by nicolevasilevsky** [comment]
pattern_name: decreasedLevelOfChemicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedLevelOfChemicalEntityInLocation.yaml
description: ""

classes:
  decreased amount: PATO:0001997
  abnormal: PATO:0000460
  chemical entity: CHEBI:24431
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  chemical_entity: "'chemical entity'"
  location: "'anatomical entity'"
 
name:
  text: "decreased level of %s in %s"
  vars:
   - chemical_entity
   - location

def:
  text: "A decrease in the level of %s in %s."
  vars:
    - chemical_entity
    - location

equivalentTo:
  text: "'has_part' some ('decreased amount' and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some 'abnormal'))"
  vars:
    - chemical_entity
    - location

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by matentzn** [comment]
Consolidated.
