### ISSUE TITLE
Review: abscess.yaml

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#329]
[abscess.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/abscess.yaml)

equivalentTo:
  text: "'has_part' some ('increased amount' and ('inheres_in' some %s and ('part_of' some %s) and ('qualifier' some 'abnormal')))"
  vars:
    - abscess
    - anatomical_entity

In the logical def, abscess is a variable, but it doesn't need to be, right? The logical def could be:

equivalentTo:
  text: "'has_part' some ('increased amount' and ('inheres_in' some abscess and ('part_of' some %s) and ('qualifier' some 'abnormal')))"
  vars:
    - anatomical_entity

**Another question** - do we want to use MPATH terms for all the phenotype ontologies?

**Comment by matentzn** [comment]
This is a very good question, and one that we will discuss soon. The more general way to phrase this is: Where do we want to integrate pathological entities across species? No answers as of yet.

**Comment by srobb1** [comment]
I was wondering does it have to be 'increased amount'?  

```
text: "'has_part' some ('abscess' and ('inheres_in' some %s) and ('qualifier' some 'abnormal'))"
```

**Comment by nicolevasilevsky** [comment]
pattern_name: abscessInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abscessInLocation.yaml
description: "The presence of an abscess in an anatomical entity."

classes:
  increased amount: PATO:0000470
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  abscess: MPATH:608

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

vars:
  anatomical_entity: "'anatomical entity'"
  abscess: "'abscess'"

name:
  text: "%s abscess"
  vars:
   - anatomical_entity

def:
  text: "The presence of an abscess of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('increased amount' and ('inheres_in' some %s and ('part_of' some %s) and ('has_modifier' some 'abnormal')))"
  vars:
    - abscess
    - anatomical_entity


@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by matentzn** [comment]
Consolidated, closing for now.
