### ISSUE TITLE
abnormal.yaml: Should 'qualifier: RO:0002573' be changed to has_modifier?

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/upheno#353]
I think the the pattern makes sense, but for consistency, should ' qualifier:RO:0002573' be 'has_modifier: RO:0002573'?

@nicolevasilevsky

**Comment by nicolevasilevsky** [comment]
I agree.
@matentzn any objections to me changing that throughout all the patterns?

**Comment by matentzn** [comment]
nope! Good call. Should always be has_modifier

**Comment by nicolevasilevsky** [comment]
this is done! yay!
