### ISSUE TITLE
review: absenceOfChemicalEntity.yaml

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#383]
[absenceOfChemicalEntity.yaml](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/absenceOfChemicalEntity.yaml)

pattern_name: absenceOfChemicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/absenceOfChemicalEntity.yaml
description: "A chemical (entity) such as sodium that is normally present is absent."

classes:
  absent: PATO:0000462
  abnormal: PATO:0000460
  chemical entity: CHEBI:24431

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  chemical_entity: "'chemical entity'"
 
name:
  text: "absent %s"
  vars:
   - chemical_entity

def:
  text: "Absent or undetectable level of %s."
  vars:
    - chemical_entity

equivalentTo:
  text: "'has_part' some ('absent' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - chemical_entity

@obophenotype/phenotype-editors could **one more person** _please_ review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by chris-grove** [comment]
Looks good. The "part_of: BFO:0000050" declaration seems unnecessary. Signing off ✅ 

Also, I'm wondering if the intention is to use this for absent biomolecules, like RNA molecules or proteins?

**Comment by balhoff** [comment]
Is everybody fine with 'absent sodium choride' being a subclass of 'absent chloride salt'? When you use the latter class, how will you know whether you are meaning a lack of any and all chloride salts, or maybe that some subtype, maybe sodium chloride, maybe potassium chloride, is missing but others could be present?

I know this is the same old issue with absence, but I think if the patterns are going to model "non-logical" absence, then the labels and definitions should clearly describe what they really mean.

**Comment by matentzn** [comment]
Closing in favour of https://github.com/obophenotype/upheno/issues/330
