### ISSUE TITLE
review: abnormalShapeOfAnatomicalEntityByShapeType 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#385]
pattern_name: abnormalShapeOfAnatomicalEntityByShapeType 
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalShapeOfAnatomicalEntityByShapeType.yaml
description: "Anatomical enity with an abnormal shape of a specified shape, i.e. columnar shaped head."

classes:
  shape: PATO:0000052
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062 

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  entity: "'anatomical entity'"
  shape: "'shape'"

name:
  text: "%s %s"
  vars:
   - shape
   - entity

annotations:
  - 
    annotationProperty: exact_synonym
    text: "abnormal %s shape of %s"
    vars:
     - shape
     - entity

def:
  text: "Any structural anomaly that causes %s to be %s shaped."
  vars:
    - entity
    - shape

equivalentTo:
  text: "'has_part' some (%s and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - shape
    - entity

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by mah11** [comment]
description text should use "e.g." ("for example"), not "i.e." ("that is")

otherwise looks good

**Comment by matentzn** [comment]
consolidated.
