### ISSUE TITLE
review: calcifiedAnatomicalEntity.yaml

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#390]
pattern_name: calcifiedAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/calcifiedAnatomicalEntity.yaml
description: ""

classes:
  calcified: PATO:0001447
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "%s calcification"
  vars:
   - anatomical_entity

annotations:
  - annotationProperty: exact_synonym
    text: "calcified %s"
    vars:
     - anatomical_entity

def:
  text: "Calcification of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('calcified' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by matentzn** [comment]
consolidated
