### ISSUE TITLE
review: increasedRateOfBehavior.yaml

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#392]
pattern_name: increasedRateOfBehavior
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/increasedRateOfBehavior.yaml
description: "Behavior occurs with a higher frequency (more often) than usual (per unit of time)"

classes:
  increased rate: PATO:0000912
  abnormal: PATO:0000460
  behavior process: NBO:0000313

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  behavior_process: "'behavior process'"
 
name:
  text: "Enhanced %s"
  vars:
   - behavior_process

def:
  text: "Enhanced or improved %s."
  vars:
    - behavior_process

equivalentTo:
  text: "'has_part' some ('increased rate' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - behavior_process
    
@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by chris-grove** [comment]
@nicolevasilevsky 
Is this ticket (now) a duplicate of #375 
?

**Comment by nicolevasilevsky** [comment]
Yes it is - I will close this one
