### ISSUE TITLE
review: abnormalPositionOfAnatomicalEntityInLocation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#394]
pattern_name: abnormalPositionOfAnatomicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalPositionOfAnatomicalEntityInLocation.yaml
description: ""

classes:
  position: PATO:0000140
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  part_of: BFO:0000050

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"
  location: "'anatomical entity'"

name:
  text: "abnormal %s topology in %s"
  vars:
   - anatomical_entity
   - location

def:
  text: "An abnormal position of the %s in the %s."
  vars:
    - anatomical_entity
    - location

equivalentTo:
  text: "'has_part' some (position and ('inheres_in' some (%s and ('part_of' some %s))) and ('has_modifier' some abnormal))"
  vars:
    - anatomical_entity
    - location

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by mah11** [comment]
I don't think FYPO has any of these, but in isolation it looks fine so I'll check it off.

**Comment by matentzn** [comment]
Consolidated for now.
