### ISSUE TITLE
review: increasedDistanceBetweenAnatomicalEntities 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#395]
pattern_name: increasedDistanceBetweenAnatomicalEntities 
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedDistanceBetweenAnatomicalEntities.yaml
description: "The distance between two anatomical entites has decreased. For example the distance between eyes."
 
classes:
  abnormal: PATO:0000460
  entity1: UBERON:0001062
  entity2: UBERON:0001062
  decreased distance: PATO:0000375

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  towards: RO:0002503

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  entity1: "'entity1'"
  entity2: "'entity2'"

name:
  text: "decreased distance between %s and %s"
  vars:
   - entity1
   - entity2

annotations:
  - 
    annotationProperty: exact_synonym
    text: "decreased distance between %s and %s"
    vars:
     - entity1
     - entity2
  - 
    annotationProperty: exact_synonym
    text: "distance decreased distance between %s and %s"
    vars:
     - entity1
     - entity2

def:
  text: "Decreased distance between %s and %s."
  vars:
    - entity1
    - entity2

equivalentTo:
  text: "'has_part' some ('decreased distance' and ('inheres_in' some %s) and ('towards' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - entity1
    - entity2

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by nicolevasilevsky** [comment]
the first synonym is the same as the label

**Comment by nicolevasilevsky** [comment]
I'm not sure if the parentheses are correct in the equiv axiom. @matentzn

**Comment by matentzn** [comment]
Consolidated.
