### ISSUE TITLE
review: decreasedWidthOfAnatomicalEntity 

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#397]
pattern_name: decreasedWidthOfAnatomicalEntity 
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/decreasedWidthOfAnatomicalEntity.yaml
description: "Decrease in the width of an anatomical entity. i.e., decreased width, skinny, tail"

classes:
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062 
  decreased width: PATO:0000599

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "decreased width of the %s"
  vars:
   - anatomical_entity

annotations:
  - 
    annotationProperty: exact_synonym
    text: "skinny %s"
    vars:
     - anatomical_entity     

def:
  text: "skinny or decreased width of the %s."
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('decreased width' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by mah11** [comment]
FYPO doesn't have any of these (though we do have a few terms mentioning cell diameter), but in isolation it looks fine so I'll check it off.
