### ISSUE TITLE
review:  increasedLengthOfAnatomicalEntity

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#399]
pattern_name: increasedLengthOfAnatomicalEntity
pattern_iri: http://purl.oboibrary.org/obo/upheno/patterns-dev/increasedLengthOfAnatomicalEntity.yaml
description: "Increased length of an antomical entity. i.e., increased length of tail"

classes:
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  increased length: PATO:0000573

relations: 
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym 

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "increased length of the %s"
  vars:
   - anatomical_entity

annotations:
  - 
    annotationProperty: exact_synonym
    text: "longer %s"
    vars:
     - anatomical_entity     

def:
  text: "longer, increased length of, %s"
  vars:
    - anatomical_entity

equivalentTo:
  text: "'has_part' some ('increased length' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
    - anatomical_entity

@obophenotype/phenotype-editors could you all review this pattern above and sign off on it in the [spreadsheet](https://docs.google.com/spreadsheets/d/1KRx7aWd53PaPEmY-xDAurcNsfHP2EFTbY-J6LzP_dvk/edit#gid=442249367).
Nico hopes to have these all reviewed by mid-March, in time for the workshop at Biocuration2019.

**Comment by matentzn** [comment]
Consolidated.
