### ISSUE TITLE
New pattern 'Triggered by X'

### ISSUE THREAD

**Issue by LCCarmody** [obophenotype/upheno#420]
We have a whole section that is 'Triggered by...' that is outside the 'Phenotypic abnormalty' hierarchy.  http://purl.obolibrary.org/obo/HP_0025204

I am not sure if it would be 'realized in response to' http://purl.obolibrary.org/obo/RO_0009501 or if another RO class would be needed.

**Comment by matentzn** [comment]
These are not phenotypes, so it is out of scope for uPheno; however, I will help sorting the patterns for HP on this one. I do however want to point out that I believe that all these clinical modifiers should not be in HP. They should be in PATO! We will discuss this; maybe put it on the agenda.

**Comment by pnrobinson** [comment]
why PATO? These definitely are human centric and are also compound (and not "atomic" qualities that PATO strives to have).

**Comment by matentzn** [comment]
I was referring to the whole clinical modifier hierarchy, and there are categories like the spatial patterns that reminded me of PATO. I just feel that many of these terms could be easily re-used across organisms, and even if they are human-centric, they are not phenotypes.. How are these used exactly? So is the idea to say something like: **phenotype A** has trigger **triggered by emotion**? Are these modifiers used in curation?

**Comment by LCCarmody** [comment]
Peter is at (was at?) a meeting with SimuConsult. Simulconsult is a commercial tool that is switching to HPO. THey have requested updates (adding terms, synonyms) to these terms. So, it is in use.

**Comment by pnrobinson** [comment]
Well actually we have had these modifiers for a year now -- read the NAR paper 2019! They are used in curation.

**Comment by matentzn** [comment]
Yes, thats fine. It is too tangential to my work to try and convince you that I believe this to be a case of scope creep. :) Let's just agree that you like these terms in HPO, and that is what matters in this case. Once I see these clincal modifier hierarchies grow a lot, I will knock again on your door, and we can have a meeting.. Good to meet you by the way, finally! :) Hope the phenopackets meeting was successful!

**Comment by pnrobinson** [comment]
@matentzn  likewise & thanks for all the awesome work!

**Comment by matentzn** [comment]
Haha thank you..
