### ISSUE TITLE
abnormal pigmentation

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#458]
There is no PATO term ' abnormal pigmentation'
I would like to convert our phenotype: 
DDPHENO:0000001 | aberrant spore color

There is normal, increased and decreased, but not **abnormal**. 

PATO_0002248 pigmented
NEW: abnormal pigmentation

I was in POTATO workshop but would appreciate input here and if approved that someone adds this term. Many thanks!

**Comment by matentzn** [comment]
Hey petra!

We are using patterns for this: 

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalPigmentationOfAnatomicalEntity.yaml

Basically, this connects PATO: degree of pigmentation with PATO:abnormal!

So in this spreadsheet we created a biocuration, just add the name of the pattern and it should work perfectly aligned with everyone else!

**Comment by matentzn** [comment]
@pfey03 closing this for now, please feel free to re-open.
