### ISSUE TITLE
question re: abnormalSizeOfAnatomicalEntity

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#461]
pattern_name: abnormalSizeOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalSizeOfAnatomicalEntity.yaml
description: "An abnormal size (the relative extent of something) of an anatomical entity, such as HP_0012504 'Abnormal size of pituitary gland'."

contributors:
- https://orcid.org/0000-0002-9900-7880
- https://orcid.org/0000-0001-9076-6015
- https://orcid.org/0000-0002-9611-1279
- https://orcid.org/0000-0002-3528-5267
- https://orcid.org/0000-0001-5208-3432
- https://orcid.org/0000-0002-1373-1705
- https://orcid.org/0000-0003-4148-4606
- https://orcid.org/0000-0002-7356-1779
- https://orcid.org/0000-0001-7941-2961
classes:
  size: PATO:0000117
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

annotationProperties:
  exact_synonym: oio:hasExactSynonym

vars:
  entity: "'anatomical entity'"

name:
  text: "abnormal size of %s"
  vars:
  - entity

annotations:
- annotationProperty: exact_synonym
  text: "abnormal size of the %s"
  vars:
  - entity

def:
  text: "A deviation from the normal size of the %s."
  vars:
  - entity

equivalentTo:
  text: "'has_part' some ('size' and ('inheres_in' some %s) and ('has_modifier' some 'abnormal'))"
  vars:
  - entity

**Comment by nicolevasilevsky** [comment]
HPO has two terms that use cells:
Abnormality of skeletal muscle fiber size
Anisopoikilocytosis

Should we create a new pattern for abnormal cell size or could we revise this pattern?

**Comment by nicolevasilevsky** [comment]
see: https://docs.google.com/spreadsheets/d/1GlZoh4kSi_xyv-m2obNdrntCg3WtB2bb58kG6w34pZc/edit#gid=1420535577

**Comment by matentzn** [comment]
Is there anyone that objects to this pattern covering cells? we will, eventually replace the fillers by OBO core terms. I definetly would have thought that cells are anatomical entities!

**Comment by nicolevasilevsky** [comment]
The cell terms are coming from the Cell Ontology

**Comment by matentzn** [comment]
yeah, i meant: UBERON:anatomical entity should subsume cells!

**Comment by sbello** [comment]
No objection to covering cells, we also use the Cell Ontology for this in the MP

**Comment by nicolevasilevsky** [comment]
Could we include cell parts as a subclass of anatomical entities too?

For example, see abnormalLevelOfCellularComponent in the [spreadsheet](https://docs.google.com/spreadsheets/d/1GlZoh4kSi_xyv-m2obNdrntCg3WtB2bb58kG6w34pZc/edit#gid=1056483432)

**Comment by matentzn** [comment]
I think cellular component might be its own category (GO?) @dosumis

**Comment by pfey03** [comment]
cell types should be fine as anatomy. Since I use the Dicty anatomy, it also includes the specific cell types that Dicty has during development and I use those.

Cellular component I raised on slack and I would like to have cellular component patterns, but not sure if anatomy gets widened to include the intracellular or if each pattern will be done for CC. Don't see an extra ticket for that yet @matentzn should I add it?

**Comment by matentzn** [comment]
So the general consensus is to have three categories for material entities:

- anatomical entities: anything from macroscopic anatomical systems (cardiovascular system) down to cells (UBERON:anatomical entity)
- Cellular Component: anything sub-cellular until individual protein (GO:cellular component)
- Chemical entity: Protein/molecular entity/ and below (Chebi:chemical entity, PR:protein)

Of course these categories are not clear cut; where the one ends and the other finishes can be quite problematic. The reason to distinguish them is that we might need some mechanism to do things like breaking part_of chains, and it is generally not unlikely that these entities will be treated differently in patterns (concentration of chemical, but not concentration of anatomical entity). 

So yes, we need patterns for sub-cellular components, and maybe we can start with abnormalCellularComponentInLocation or something simple like that!

**Comment by matentzn** [comment]
The discussion above is fully reconciled. Closing for now.
