### ISSUE TITLE
question re: decreasedLevelOfMolecularEntityInALocation

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#462]
these HPO terms use PRO terms, but otherwise fit the pattern: decreasedLevelOfMolecularEntityInALocation

ID | Label
-- | --
http://purl.obolibrary.org/obo/HP_0003073 | Hypoalbuminemia
http://purl.obolibrary.org/obo/HP_0010683 | Low tissue non-specific alkaline phosphatase
http://purl.obolibrary.org/obo/HP_0410188 | Decreased glucose-6-phosphate dehydrogenase level in red blood cells
http://purl.obolibrary.org/obo/HP_0410190 | Decreased glucose-6-phosphate dehydrogenase level in leukocytes
http://purl.obolibrary.org/obo/HP_0410179 | Decreased glucose-6-phosphate dehydrogenase level in blood
http://purl.obolibrary.org/obo/HP_0410187 | Decreased glucose-6-phosphate dehydrogenase level in tissue
http://purl.obolibrary.org/obo/HP_0040216 | Hypoinsulinemia
http://purl.obolibrary.org/obo/HP_0003292 | Decreased serum leptin
http://purl.obolibrary.org/obo/HP_0003351 | Decreased circulating renin level
http://purl.obolibrary.org/obo/HP_0010837 | Decreased serum ceruloplasmin

Should we create a new pattern or expand the existing pattern?

**Comment by matentzn** [comment]
I think: clear yes! Disagreements?

**Comment by LCCarmody** [comment]
I think they work.

**Comment by chris-grove** [comment]
I think it's fair to include PRO classes representing molecules as molecular/chemical entities. Just to be clear, we are now referring to this pattern:

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyDecreasedLevelOfChemicalEntityInLocation.yaml

correct?

**Comment by nicolevasilevsky** [comment]
yes, that is right, Chris
