### ISSUE TITLE
question: abnormal X

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#463]
https://docs.google.com/spreadsheets/d/1GlZoh4kSi_xyv-m2obNdrntCg3WtB2bb58kG6w34pZc/edit#gid=908639811

This tab named abnormalAnatomicalEntity described abnormal anatomical entities (and some cells, behaviors and protein), but we don't currently have a pattern for this, do we?

**Comment by matentzn** [comment]
https://github.com/obophenotype/upheno/tree/master/src/patterns/dosdp-patterns

In there!

**Comment by nicolevasilevsky** [comment]
ah, thanks! :)
