### ISSUE TITLE
pattern is missing location

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#472]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation.yaml

This pattern is missing the location, right?

Shouldn't it be:

pattern_name: abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyDecreasedFunctionalityOfAnatomicalEntityInLocation.yaml
description: ""

contributors:
- https://orcid.org/0000-0001-5208-3432
classes:
  decreased functionality: PATO:0001624
  abnormal: PATO:0000460
  anatomical entity: UBERON:0001062
  independent continuant: BFO:0000004

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051

vars:
  anatomical_entity: "'anatomical entity'"
  entity: "'independent continuant'"

name:
  text: "%s dysfunction in %s"
  vars:
  - anatomical_entity
  - entity

def:
  text: "A functional abnormality of the %s in %s."
  vars:
  - anatomical_entity
  - entity

equivalentTo:
  text: "'has_part' some ('decreased functionality' and ('inheres_in' some (%s and ('part_of' some %s))) and  ('has_modifier' some 'abnormal')"
  vars:
  - anatomical_entity
  - entity

**Comment by nicolevasilevsky** [comment]
this one too:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedFunctionalityOfAnatomicalEntityInLocation.yaml

**Comment by matentzn** [comment]
Cool works!

**Comment by nicolevasilevsky** [comment]
I updated these patterns, closing
