### ISSUE TITLE
deprecate pattern: abnormallyLackingAllPartsOfTypeAnatomicalEntity

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#473]
per the POTATO mtg today, it was suggested that these patterns be deprecated:

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyLackingAllPartsOfTypeAnatomicalEntity.yaml

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyLackingAllPartsOfTypeAnatomicalEntityInLocation.yaml

**Comment by matentzn** [comment]
Deprecated
