### ISSUE TITLE
Suggestions for pattern listings README files

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#480]
This concerns patterns listed in README files like:

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/README.md

One request: list the patterns alphabetically by pattern name

**Comment by matentzn** [comment]
Fixed. Please re-open whenever new suggestion comes up.

**Comment by sbello** [comment]
In the README.md file for Abnormal has fewer parts of type anatomical entity and Abnormal has fewer parts of type anatomical entity in location there is a suggestion to use decreased number instead. Should we have a similar suggestion for Abnormal has extra parts of type anatomical entity and Abnormal has extra parts of type anatomical entity in location and increased number?

**Comment by sbello** [comment]
The purl for Abnormally closed anatomical entity (http://purl.obolibrary.org/obo/upheno/patterns/abnormallyClosedAnatomicalEntity.yaml) is giving a 404 error

**Comment by matentzn** [comment]
thanks @sbello 

I expect at least 10 more 404s, let me know when you encounter them!
