### ISSUE TITLE
review: abnormalDevelopmentOfAnatomicalEntity

### ISSUE THREAD

**Issue by chris-grove** [obophenotype/upheno#487]
Here is the new pattern proposal:

```
pattern_name: abnormalDevelopmentOfAnatomicalEntity
pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalDevelopmentOfAnatomicalEntity.yaml
description: "A phenotype in which an organism exhibits an abnormal development of some anatomical entity. For example, abnormal development of the heart."

contributors:
- https://orcid.org/0000-0001-9076-6015

classes:
  process quality: PATO:0001236
  abnormal: PATO:0000460
  developmental process: GO:0008150
  anatomical entity: UBERON:0001062

relations:
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  results_in_developmental_progression_of: RO:0002295

vars:
  anatomical_entity: "'anatomical entity'"

name:
  text: "abnormal development of %s"
  vars:
  - anatomical_entity

def:
  text: "An abnormal development of the %s."
  vars:
  - anatomical_entity

equivalentTo:
  text: "'has_part' some ('process quality' and ('inheres_in' some ('developmental process' and ('results_in_developmental_progression_of' some %s))) and  ('has_modifier' some 'abnormal'))"
  vars:
  - anatomical_entity
```

This proposal is in lieu of, for example, using the abnormalBiologicalProcessInLocation pattern with 'developmental process' as the pattern and some anatomical entity as the location since the developmental process does not always necessarily inhere_in the same anatomical entity that is being developed, but rather often in some progenitors of the final structure.

Comments and suggestions welcome.

**Comment by chris-grove** [comment]
And here is the current branch URL to the pattern (in dosdp-workshop):

https://github.com/obophenotype/upheno/blob/New-pattern-proposal-abnDevOfAnatEnt-July-8-2019/src/patterns/dosdp-workshop/abnormalDevelopmentOfAnatomicalEntity.yaml

**Comment by matentzn** [comment]
@chris-grove is results_in_developmental_progression_of the official relation used in GO?

**Comment by chris-grove** [comment]
@matentzn 
I'm not sure, I was just looking for what seemed to be the most appropriate relation in RO. How would I check?

**Comment by matentzn** [comment]
I also tried to search for this, but could not find the appropriate relation. @dosumis should be able to help? I think the sub-tree we need to search is [anatomical structure development](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http://purl.obolibrary.org/obo/GO_0048856)

**Comment by pfey03** [comment]
Could the Pattern be 
 **abnormalDevelopmentORCellDifferntiationOfAnatomicalEntity?**

I have DDPHENO terms that are in GO a child of development and that is 'cell differentiation' such as DDPHENO:0000098 | aberrant prestalk A cell differentiation

GO has GO:0031149 | sorocarp stalk cell differentiation
but no children such as prestalk A or prestalk B cells and won't add these I think. 
Thanks!

**Comment by dosumis** [comment]
Looks like this should have been linked to this merged pull request: https://github.com/obophenotype/upheno/pull/486 - and closed by the merge.  Closing it now and moving Petra's comment to a new ticket: #505

**Comment by chris-grove** [comment]
@dosumis 
Whoops! Thanks!
