### ISSUE TITLE
add pattern for abnormal cellular component

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#493]
I have DDPHENO:0000053: decreased contractile vacuole size 
contractile vacuole: GO:0000331

We also have
 DDPHENO:0000517:  abolished localization to contractile vacuole
 DDPHENO:0000272: increased number of mitochondria

Always need (maybe very few exceptions)
aberrant (abnormal)
increased
decreased
abolished

Thanks!

**Comment by matentzn** [comment]
so you need:

- abnormalCellularComponent (unspecified abnormality of a cellular component)
- increasedNumberOfCellularComponent (the whole organism has more mitochondria; or do you perhaps need increasedNumberOfCellularComponentInALocation (mor mitochondria in epithelial cells)
- decreasedNumberOfCellularComponent

But abolished? abolished is a process quality. So you mean to say that the creation of a particular cellular component is abolished? abolished localisation; what does that mean exactly?

**Comment by pfey03** [comment]
@matentzn 
It's true, abolished number doesn't exist. And most organelles are essential. 
But abnormal / increase/ decreased for these should do

Localization to CC is a different thing and I should not have mixed it in above.

In Dicty cellular components are simple as there is only one amoeba cell when they are in vegetative, feeding stage. so for me, I won't need location for abnormal CC number / size/ 

maybe come across others will add it here
Thanks!

**Comment by matentzn** [comment]
We currently have:

- [X]  https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalFunctionalityOfCellularComponent.yaml
- [X] https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalMorphologyOfCellularComponent.yaml
- [X] https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyAlteredNumberOfCellularComponent.yaml
- [X] https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyDecreasedNumberOfCellularComponent.yaml
- [X] https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedNumberOfCellularComponent.yaml

Please open new ticket if other patterns are required!
