### ISSUE TITLE
abnormalCellDifferentiation (and relationship to abnormalDevelopmentAnatomicalStructure))

### ISSUE THREAD

**Issue by dosumis** [obophenotype/upheno#505]
(Moved from #487) - @pfey03 wrote:

> Could the Pattern be
> abnormalDevelopmentORCellDifferntiationOfAnatomicalEntity?

> I have DDPHENO terms that are in GO a child of development and that is 'cell differentiation' such as DDPHENO:0000098 | aberrant prestalk A cell differentiation

> GO has GO:0031149 | sorocarp stalk cell differentiation 
> but no children such as prestalk A or prestalk B cells and won't add these I think.
> Thanks!

**Comment by dosumis** [comment]
Hi Petra,

We could add a new pattern for AbnormalCellDifferentiation.  Terms defined using this will nest automatically under abnormalDevelopmentAnatomicalStructure.   Having this more specific pattern will be good for maximising integration with GO.

**Comment by dosumis** [comment]
The  relevant GO pattern appears to be:


'cellular developmental process' and ('results in acquisition of features of' some {cell})


![image](https://user-images.githubusercontent.com/112839/62119736-19515d00-b2b8-11e9-89a2-a6b4c65abd14.png)

Note - sorocarp stalk cell differentiation terms in GO are not linked to cell type terms.  Maybe request they refer to DDANAT?  Or is there a more suitable general anatomy ontology you could use for cell type terms?

**Comment by pfey03** [comment]
@dosumis Thanks a lot David for the specific pattern.!
I can discuss in GO to link those terms to DDANAT. Historically, the Dicty cell types where in cell but they were obsoleted. Thus now it's DDANAT for all specific Dicty cell types.

**Comment by matentzn** [comment]
@dosumis 

> 'cellular developmental process' and ('results in acquisition of features of' some {cell})

Is this the EQ for abnormalCellDifferentiation? I can create the pattern.

**Comment by matentzn** [comment]
new cell differentiation pattern proposal: https://github.com/obophenotype/upheno/pull/516/files

**Comment by matentzn** [comment]
> Terms defined using this will nest automatically under abnormalDevelopmentAnatomicalStructure.

I think it would nest under abnormal development, but not abnormalDevelopment of anatomical structure (think of relation of 'results in acquisition of features of' and 'occurs in')

**Comment by dosumis** [comment]
> > Terms defined using this will nest automatically under abnormalDevelopmentAnatomicalStructure.

> I think it would nest under abnormal development, but not abnormalDevelopment of anatomical structure (think of relation of 'results in acquisition of features of' and 'occurs in')

? Don't follow.  cell SubClassOf  'anatomical structure'.  Not sure what occurs_in has to do with this.

We need pattern.owl files for uPheno so we can get instant feedback on these questions.  Did you get round to having these be build with imports as part of ODK?

**Comment by matentzn** [comment]
Ah you have not seen my new most favourite issue:

https://github.com/obophenotype/upheno/issues/510

A major revision of pattern.owl is underway, and I am loving it! Feel free to check 
https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/pattern.owl

However, only existing patterns are in there; not the ones for which we only have PRs so far. Pretty excited about pattern.owl! We are doing some cool work using pattern.owl to perfecting our uPheno patterns right now.

Sorry about `occurs in`, was a mix up, should have checked. So the situation is this:

- abnormalDevelopmentOfAnatomicalEntity: "'has_part' some ('process quality' and ('inheres_in' some ('developmental process' and (`'results_in_developmental_progression_of'` some %s))) and  ('has_modifier' some 'abnormal'))"
- abnormalCellDifferentiation: "'has_part' some ('process quality' and ('inheres_in' some ('cellular developmental process' and (`'results_in_acquisition_of_features_of'` some %s))) and  ('has_modifier' some 'abnormal'))"

Only if `results_in_acquisition_of_features_of` is a subrole of `results_in_developmental_progression_of` (which may be, you know this better),  abnormalCellDifferentiation will classify under abnormalDevelopmentOfAnatomicalEntity.

**Comment by dosumis** [comment]
It is:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/112839/62625618-8c19a280-b960-11e9-97d4-5bbb07c6f94c.png">

(which is why I chose the pattern), but for some reason we're not getting  inferred classification:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/112839/62625713-bc614100-b960-11e9-871b-04422c76fe14.png">

**Comment by matentzn** [comment]
It appears that `CL_0000000` which we use as a filler for cell types and `UBERON_0001062` (anatomical entity) are not aligned anywhere in CL or UBERON. I was wondering about that. Where is it, if anywhere, and where should this axiom be?

**Comment by balhoff** [comment]
@matentzn take a look at the bridge ontologies here: http://uberon.github.io/downloads.html#bridge

I think both should be bridged to a CARO term, but I'm not sure there is a connection from `CL_0000000` to `UBERON_0001062`. Seems like there should be, unless  `UBERON_0001062` is considered animal-specific.

**Comment by matentzn** [comment]
Ahh yea. According to the [caro-uberon](http://ontologies.berkeleybop.org/uberon/bridge/uberon-bridge-to-caro.owl) bridge, `UBERON_0001062=CARO_0000000`, and the cl-caro bridges say CARO_0000013=CL_0000003. Which solves it all. It also adds another consideration: instead of using CL_0000000 for patterns, we should use the less general [CL_0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000003). Thanks @balhoff 

This add another con

**Comment by matentzn** [comment]
@dosumis 

1. Do you find [CL_0000003](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000003) or [CL_0000000](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000000) more appropriate for:
- abnormalCellProliferationActingOnCellsOfTypeInLocation.yaml
  - abnormalCellDifferentiation.yaml
  - abnormalCellProliferationActingOnCellsOfType.yaml

2. Are you happy with this assumption `UBERON_0001062=CARO_0000000` in the uberon caro bridge, or do you prefer to think of it as `UBERON_0001062 SUB CARO_0000000` and change the pattern scope everywhere from [UBERON_0001062](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001062) to [CARO_0000000](https://www.ebi.ac.uk/ols/ontologies/caro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCARO_0000000)?

**Comment by dosumis** [comment]
> instead of using CL_0000000 for patterns, we should use the less general CL_000000 <https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000003>3

I think so.  The broader term covers cells in culture.  I’m not sure it makes sense to talk about abnormal cell differentiation in synthetic systems.

**Comment by matentzn** [comment]
I have:

- changed the range of the Cell patterns to CL:'native cell'
- Imported the CARO UBERON bridge (reasoning times with HermiT jumped up considerably, but doable)
- Fixed another broken (abscessInLocation) pattern that was identified through the CARO import
- saved pattern.owl as the inferred class hierarchy now; so no need to run reasoner.

Now: abnormalCellDifferentiation classifies under abnormalDevelopmentOfAnatomicalEntity! 

![image](https://user-images.githubusercontent.com/7070631/62776210-d0f92280-baa1-11e9-8107-9b394a54d076.png)

I love pattern.owl as a tool for managing large numbers of complex patterns; to be honest, now that I say HOW effective this really is, I think we can comfortably manage 500+ patterns.
