### ISSUE TITLE
MP:0005508 and HP:0011842 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#51]
Originally reported on Google Code with ID 50

```
MP:0005508 and HP:0011842 should be inferred or asserted to be equivalent!
```

Reported by `dr.sebastian.koehler` on 2014-08-07 15:07:25

**Comment by nicolevasilevsky** [comment]
These two terms have the same logical def, i think this ticket can be closed. Please reopen if not.
