### ISSUE TITLE
need abnormal size cellular component patterns

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#567]
abnormalSize OfCellularComponent
abnormallyDecreasedSizeOfCellularComponent
abnormallyIncreasedSizeOfCellularComponent

Thanks!

**Comment by matentzn** [comment]
Thanks Petra. We will add them in the next round of upheno patternising.. Until then feel free to create the tsvs - patterns will come.

**Comment by pfey03** [comment]
@matentzn thanks and have a nice weekend!

**Comment by nicolevasilevsky** [comment]
closing, duplicate.
