### ISSUE TITLE
which pattern to use for cysts?

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/upheno#611]
Peter and Sue- 
I see HPO and MP seems to use a combination of two patterns for cysts. Could we agree on a single pattern? (I will update HPO)

**_HPO example:_**
**HP_0006799 | Basal ganglia cysts**
'has part' some 
    (cystic
     and ('inheres in' some 'basal ganglion')
     and ('has modifier' some abnormal))

**HP_0001407 'Hepatic cysts'**
'has part' some 
    ('increased amount'
     and ('inheres in' some 
        (cyst
         and ('part of' some liver)))
     and ('has modifier' some abnormal))

**_MP examples:_**

**MP_0009737 'prostate gland cysts'**
'has part' some 
(cystic and ('inheres in' some 'prostate gland') and ('has modifier' some abnormal))

**MP_0003336 'pancreas cysts'**
'has part' some 
('increased amount' and ('inheres in' some 
(cyst and ('part of' some pancreas))) and ('has modifier' some abnormal))

**Comment by pnrobinson** [comment]
I am fine for moving to the MP patterns. Where does the term 'cyst' come from though?

**Comment by matentzn** [comment]
MPATH

**Comment by matentzn** [comment]
I think you and @sbello also need to think which pattern makes more sense internally - logically the MPATH (inheres in cyst) and PATO (cystic) patterns are incompatible, so it a decision should be made here which way to go. Whatever the decision maybe it makes sense to go the same way with

inheres in MPATH:lesion vs PATO:lesioned.

**Comment by pnrobinson** [comment]
I think in principle both solutions are fine but we should choose one and be consistent (also across related lesion terms!)

**Comment by matentzn** [comment]
Agreed!

**Comment by sbello** [comment]
I would vote for using the PATO term as PATO has polycystic and monocystic as child terms of cystic and this allows us to create an eq for terms like polycystic kidney (http://purl.obolibrary.org/obo/MP_0008528) that is clearly distinct from the parent term 'kidney cysts'. I don't see how we would do that with the MPATH term.

**Comment by nicolevasilevsky** [comment]
thanks @sbello. I will do a PR to revise the current pattern
