### ISSUE TITLE
New pattern: abnormalSizeOfCellularComponent

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#627]
I have phenotypes such as

- small pinosomes
- decreased contractile vacuole size
- increased phagolysosome size

Thanks!

**Comment by mah11** [comment]
This will be useful for us too - we have things like "enlarged nucleus" and others.

**Comment by pfey03** [comment]
@nicolevasilevsky @matentzn 
Hello, could you please add this pattern?
abnormal
decreased
increased

Many thanks!!

**Comment by nicolevasilevsky** [comment]
I'll take care of it, @pfey03!

**Comment by pfey03** [comment]
Oh just saw I added this twice as it's been so long waiting
https://github.com/obophenotype/upheno/issues/567

**Comment by nicolevasilevsky** [comment]
Oh, actually @pfey03 I think you can use this pattern for cellular components:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalSizeOfAnatomicalEntity.yaml

**Comment by nicolevasilevsky** [comment]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyDecreasedSizeOfAnatomicalEntity.yaml

https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedSizeOfAnatomicalEntity.yaml

**Comment by nicolevasilevsky** [comment]
oh wait, I'm wrong! I'll add these new patterns

**Comment by nicolevasilevsky** [comment]
@pfey03 do you want to check the linked PRs before I merge?

**Comment by nicolevasilevsky** [comment]
I'll go ahead and merge, we can fix any issues later :)

**Comment by nicolevasilevsky** [comment]
Closing. @pfey03 if you see any issues, please let me know.
