### ISSUE TITLE
Review: blisteredAnatomicalEntityInLocation.yaml

### ISSUE THREAD

**Issue by srobb1** [obophenotype/upheno#632]
I think it would be good to have a description of what a blister is in the definition.

current:
```
def:
  text: "An abnormally blistered %s in %s."
```

propsoed:
```
def:
  text:  "Abnormal local accumulation of fluid underneath the surface causing a blistered %s in %s"
```

**Comment by matentzn** [comment]
Cant help with that. Agree that a definition of blister would be good. Could you make an respective PR?

**Comment by nicolevasilevsky** [comment]
I like your suggested revision @srobb1

**Comment by srobb1** [comment]
I will make a pull request

**Comment by srobb1** [comment]
Poop, i committed without making a pull request. https://github.com/obophenotype/upheno/commit/4ff80bb7c0d7125ef58f556d2da6153be3b47bc3

So rude. Sorry :(

**Comment by srobb1** [comment]
https://github.com/obophenotype/upheno/pull/644
https://github.com/obophenotype/upheno/pull/643

**Comment by nicolevasilevsky** [comment]
> Poop, i committed without making a pull request.

I accidentally do that sometimes too!

**Comment by srobb1** [comment]
all resolved
