### ISSUE TITLE
new term Inflammatory_myofibroblastic_tumor

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#65]
Originally reported on Google Code with ID 64
```
new term :
Inflammatory_myofibroblastic_tumor
http://en.wikipedia.org/wiki/Inflammatory_myofibroblastic_tumour

perhaps a subtype of fibroma (HP:0010614) ?
```

Reported by `nicole.l.washington` on 2015-01-21 06:50:38

**Comment by drseb** [comment]
moved to https://github.com/obophenotype/human-phenotype-ontology/issues/789
