### ISSUE TITLE
question about distal muscles

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#69]
Originally reported on Google Code with ID 68

```
Do distal muscles refer to muscles below the elbow and knees?
```

Reported by `vasilevs@ohsu.edu` on 2015-02-09 21:57:44

**Comment by cmungall** [comment]
Seems so

see

[!][img](https://www.mda.org/sites/default/files/Overview-body_distalMD.jpg)

From https://www.mda.org/disease/distal-muscular-dystrophy
