### ISSUE TITLE
New pattern: abnormal acidity of anatomical entity

### ISSUE THREAD

**Issue by jseager7** [obophenotype/upheno#691]
We have a few terms in PHIPO that describe changes in pH of an entity. Here's one example:

'abnormal pH within a pathogen host interaction' ([PHIPO:0001109](http://purl.obolibrary.org/obo/PHIPO_0001109))
> a pathogen host interaction phenotype where the pH in a pathogen or host cell or cellular component is abnormal.

I think that the 'acidity' quality from PATO captures changes in pH ([PATO:0001842](http://purl.obolibrary.org/obo/PATO_0001842)). I asssume that 'anatomical entity' (UBERON:0001062) covers cells and cellular components as well.

Note that most of the PHIPO terms in question are related to pathogen-host interactions, so they probably can't be logically defined yet, because of the extra contextual information that would be needed in those cases. So if you'd prefer not to create patterns until they're definitely needed, this can afford to wait.

**Comment by sbello** [comment]
Discussed at the editors call:
Agree that PATO term is correct

Question from the editors call - is this always anatomy or is this subcellular?

Patterns are set that anatomical entity covers down to cell, cellular component covers below cell but bigger than chemical entity/protein (bit fuzzy at the small end)

We think you would need to patterns one for anatomical entity and one for cellular component, unless we can find an ontology with a grouping term.

We can create the acidity pattern(s) if you want.

**Comment by jseager7** [comment]
Thanks for the feedback. With regards to PHIPO, the pH phenotypes are a subclass of cellular phenotypes: specifically 'pathogen-host interaction cell phenotype' (PHIPO:0000510), which is (textually) defined as a "phenotype observed at the level of an individual cell", while its subclasses relate to the pH of cellular components (such as the phagolysosome).

The main problem with these PHIPO pH phenotypes is that they relate to pathogen-host interactions (specifically, the pH of the host organism in a pathogen-host interaction), and uPheno currently doesn't have any means to model these interactions with phenotype patterns. Currently, we don't have any terms in PHIPO that describe pH change for a single organism outside of the context of a pathogen-host interaction, so I don't think we'd have an immediate use for 'increased acidity of anatomical entity', for example. We can't naively apply these patterns to pathogen-host interactions because it's not clear from the pattern whether the pH change should apply to the pathogen or the host.

So, I don't think there's any need to create the patterns at the moment, especially if uPheno's policy is to not create patterns until there is a clear need for them. Maybe the terms would be useful for other ontologies, but I have no problem with this issue being closed until PHIPO (or someone else) actually needs the patterns.

**Comment by matentzn** [comment]
Thank you @jseager7 !

**Comment by dosumis** [comment]
Closing as seems not needed for now.  

Note - for host pathogen interactions, consider using existing GO term as the entity.
