### ISSUE TITLE
new pattern: abnormallyDetachedAnatomicalEntities

### ISSUE THREAD

**Issue by sbello** [obophenotype/upheno#692]
we need a pattern to model abnormal detachment of an entity from another entity
example: detached Reissner membrane (http://purl.obolibrary.org/obo/MP_0006023)
modification of https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormallyFusedAnatomicalEntities.yaml
Just need to swap out fused (PATO:0000642) and replace with detached from (PATO:0001453)

**Comment by anna-anagnostop** [comment]
Pattern needs to be corrected to:

**Comment by sbello** [comment]
I don't think this would be 'characteristic of part of'. We wouldn't want to say for example that a detached retina was a detached eye.
