### ISSUE TITLE
new pattern: decreased / increased stability of anatomical entity

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#700]
PATO:0015028 - decreased stability
PATO:0015027 - increased stability

I need the phenotype:
decreased spore stability 

DDANAT:0000414 - spore

I hope this is useful for others too.
Thanks!

**Comment by matentzn** [comment]
Thanks @pfey03 

@nicolevasilevsky would you be able to take care of these three:

- [ ] abnormalStabilityOfAnatomicalEntity
- [ ] abnormallyIncreasedStabilityOfAnatomicalEntity
- [ ] abnormallyDecreasedStabilityOfAnatomicalEntity

Can you make sure that it is clearly understood what "stability" means? PATO is not very clear about it, maybe this helps:
https://github.com/pato-ontology/pato/issues/113

**Comment by nicolevasilevsky** [comment]
confirming a spore is a cell

**Comment by pfey03** [comment]
@matentzn @nicolevasilevsky  sorry responding so late.
Since Dicty is not Uberon and not in Cell Types, every part is in Dicty anatomy and not outside vocabularies. Spore is an anatomical entity for us and yes, it's also a cell, but we do not have the luxury of differenciating.
Thanks @nicolevasilevsky for adding the patterns I hope it's useful for other organisms.

**Comment by matentzn** [comment]
Yeah dont worry for now about that - this thing with cell vs single cell organism is a bit.. of an artificial problem.

**Comment by pfey03** [comment]
For history: Dicty cells were in Cell Ontology but were kicked out quite a while ago. But we have DDANAT taking care of all.

**Comment by matentzn** [comment]
I am closing this, please open a new ticket if we missed something!
