### ISSUE TITLE
new patterns: developmental processes that are not in the GO

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#712]
We have many phenotypes describing distinct parts of development that are not in the GO. This is because GO and Phenotype annotations may overlap a bit but should not be redundant.

For example (aberrant/abolished/increased/decreased/precocious/delayed)
- tip formation - this is the tip that forms at late aggregation  
- basal disc formation - this is at the base of the stalk
- slug migration - D. discoideum slugs are photo- and chemotactic and migrate before culmination
- prestalk cell differentiation - we also have specifics prestalk A, prestalk 0 etc. 
- prespore cell differentiation
- sorting to prestalk region

I could adapt these phenotypes a bit and would need patterns to use the Dicty anatomy. all the cells and other parts are in DdANAT.

e.g 
-  slug migration: I might use  abnormalMotilityOfAnatomicalEntity and need the absence/increased/decreased qualifiers
-  tip formation: **new pattern** abnormalDevelopmentOfAnatomicalEntity - I could change phenotype to 'development of the tipped mound'
-  prestalk cell differentiation: **new pattern** abnormalDifferentiationOFAnatomicalEntity  Or maybe I can use abnormalCellDifferentiation and use our DDANAT instead of CL?

 Maybe I only need one new pattern family: abnormalDevelopmentOfAnatomicalEntity
Thanks, solving these would help me a lot.

**Comment by matentzn** [comment]
hey @pfey03 

For abnormalDevelopmentOfAnatomicalEntity there already is a pattern you can use, which is perfect for your case:

http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalDevelopmentOfAnatomicalEntity.yaml

For the differentiation, yes, use the cell differentiation one! We will align ddanat with CL at some point here!

For the other ones, can you create separate tickets? Thaanks!

**Comment by pfey03** [comment]
@matentzn Sorry for late response it was these grant progress reports that took me out for a couple of weeks. 
I need children of the existing patterns:
- abnormalDevelopmentOfAnatomicalEntity
-- abnormallyDelayedDevelopmentOfAnatomicalEntity
plus precocoius, abolished / absenceOF

-  abnormalCellDifferentiation
-- abnormallyDecreasedCellDifferentiation
plus increased, abolished / absenceOF

Thanks!

**Comment by sbello** [comment]
Discussed on the editor's call

- Will GO not take these?
- Possibly these are too detailed for GO
- Could we have a pattern(s) that is development/formation of anatomical entity
- We've done this for other cases.
- Something along the lines of "'anatomical structure development' and ('results in development of' some sorus)"

**Comment by dosumis** [comment]
Discussed on the editor's call

- Will GO not take these?
- Possibly these are too detailed for GO
- For generic abnormal development - use http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormalDevelopmentOfAnatomicalEntity.yaml
  - If we don't already have them we should include patterns for delayed, premature and absent (@pfey03 to confirm)

For more specific types of developmental process we need to use the more specific GO patterns for composite entities:
'cell differentiation'
 and ('results in acquisition of features of' some 'acinar cell')
In this case we need versions with increased/decreased/premature/delayed/absent 

For formation:
'anatomical structure formation involved in morphogenesis'
 and ('results in formation of' some 'abducens nerve')
In this case we need premature/delayed/absent

**Comment by pfey03** [comment]
@dosumis @matentzn 
Meantime I solved several of these differently, often  with abnormalBiologicalProcessinLocation pattern e.g BP cell differentiation with DDANAT term as UBERON is allowed in Location so is DDANAT.

The cell sorting phenotypes I can probably also solve with GO process: cell migration. I often use exact GO terms as synonyms as those are often less precise or unusual of what's used typically in Dicty research.

tip development I will change to 'sorocarp development of tipped mound' (synonym), maybe primary term 'development of tipped mound' and I can also use  abnormalBiologicalProcessinLocation

Finally, slug migration solving with GO:locomotion is in the other open issue  https://github.com/obophenotype/upheno/issues/714

Maybe this issue can be closed.

**Comment by matentzn** [comment]
Thank you so much @pfey03 Let us know when we should reopen! :)
