### ISSUE TITLE
new patterns: - abnormalMotilityOfAnatomicalEntity and children

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#714]
I need new patterns for what in Dicty is investigated, e.g. slug migration, or slug motility. slugs during development are photo and thermostatic and move towards these sources, for a better location near the surface to culminate and sporulate.

- abnormalMotilityOfAnatomicalEntity
please also add:
Decreased
Increased
Abolished/AbsenceOF

Thanks!

**Comment by matentzn** [comment]
We have https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-dev/abnormalMotilityOfCellularComponent.yaml

If we add the increased/decreased patterns, would that work? What exactly is the entity that loses motility?

**Comment by pfey03** [comment]
These are **not cellular components (GO)**, these are anatomical entities, in Dicty's case as it develops the whole developing entity. @matentzn the MotilityOFCellularComponent does not work for these phenotypes: aberrant/abolished/decreased/increased slug migration (motility = synonym) 
We have 202 annotations to such terms.

I could see that in higher organisms, anatomical entities can also move abnormally during development, for example.
Thanks!

**Comment by matentzn** [comment]
Need @dosumis help here

**Comment by dosumis** [comment]
Editor's call discussion - Use GO:locomotion instead.

**Comment by dosumis** [comment]
@pfey03 - Please draft pattern as agreed above.

**Comment by pfey03** [comment]
OH @dosumis  and all, since I work on so many fronts and have progress report to do, I solved this. I solved it with GO term 'locomotion'. For example:
'aberrant slug migration' , I added exact synonym: 'aberrant migratory slug locomotion'
pattern: abnormalBiologicalProcessInLocation 

DDPHENO:0001077 | aberrant slug migration | GO:0040011 | locomotion | DDANAT:0000008 | migratory slug

So I can also easily do in/decreased and absence without trouble.

If only me wanted this issue can be closed, sorry about forgetting about this here.

**Comment by pfey03** [comment]
@dosumis @matentzn 
I have a lot of annotations to this phenotype and it's children increased/decreased/absent

DDPHENO:0000306
name: aberrant sorting to prestalk region

This is  pretalk cell sorting or motility during sorocarp development. Typically in the slug stage when final sorting of prestalk cells to the front / tip of the migratory slug happens, this movement of cells is often disturbed in mutants.

Doesn't movement of cells to correct spot happen in many organisms during development? How do others annotate these abnormal cell movements during development?

Maybe a pattern:
abnormalMotilityOfAnatomicalEntityDuringBiologicalProcess  

GO:0031153. slug development involved in sorocarp development

Thanks!

**Comment by matentzn** [comment]
I marked it for discussion at editors call but as our agenda is already quite full, it would be good to answer this question @dosumis.

**Comment by pfey03** [comment]
I solved all this differently. With changing terms slightly and adding synonyms to match to GO 'locomotion' or 'cell migration'. This pattern not needed anymore. Closing
