### ISSUE TITLE
meiotic drive - phenotype or biological process?

### ISSUE THREAD

**Issue by cmungall** [obophenotype/upheno#717]
meoitic drive is a phenotype in MP (under abnormal meiosis) and hence upheno. It is also the name of a biological process

```
id: GO:0110134
name: meiotic drive
namespace: biological_process
def: "A biological process that results in the unequal transmission of alleles, haplotypes, or chromosomes from a parental genome to gametes. In the absence of meiotic drive, the two copies of each gene or chromosome in a diploid organism are transmitted to offspring with equal probability, whereas meiotic drive results in overrepresentation of the driving allele among the surviving products of meiosis." [GOC:mah, PMID:26920473, PMID:29322557, PMID:29499907]
subset: goslim_pombe
is_a: GO:0022414 ! reproductive process
```

the MP term doesn't seem to have been used for annotation:
http://www.informatics.jax.org/vocab/mp_ontology/MP:0010032 no annotations

(I believe there have been transgenic studies with mouse gene drives?)

meoitic drive is in GO as it's a 'normal' evolved process and not abnormal.. widespread across taxa, I believe even in mouse, so it's not clear this should be under abnormal meiosis. Maybe the MP term should be for experimentally induced gene drives? What should the relationship to the GO process be?

**Comment by dosumis** [comment]
Agree.  @sbello - is there a case for keeping the MP term?  We could always derive a phenotype term from the GO term if there is a need to record some disruption in the process.

**Comment by sbello** [comment]
Creating a ticket for the MP to obsolete this term. It should not have been put in the MP. We may want a term for abnormal meiotic drive for cases where the mutation alters the process but the process term should not be in the MP.

**Comment by sbello** [comment]
removed from MP, replaced with abnormal meiotic drive term
