### ISSUE TITLE
Add abnormalRateOfBiologicalProcessInLocation.yaml

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/upheno#724]
Please consider adding new pattern: 
abnormalRateOfBiologicalProcessInLocation.yaml

We already have abnormallyIncreasedRateOfBiologicalProcessInLocation.yaml and abnormallyDecreasedRateOfBiologicalProcessInLocation.yaml

Thanks,

Anna

**Comment by matentzn** [comment]
Thank you Anna! Seems to have been an oversight!

**Comment by sbello** [comment]
I would suggest modifying the current definition: 
"Changed frequency of some biological process occurring (per some unit of time)."
to
Change in the occurrence per unit time of a {biological process}.

Similarly the definitions of the related decreased, increased and in location terms should be changed 
Decrease/Increase in the occurrence per unit time of a {biological process}.
Decrease/Increase in the occurrence per unit time of a {biological process} in the {anatomical term}.

This would give us, for example
decreased renal blood flow rate 
def: Decrease in the occurrence per unit time of some blood circulation in the kidney (Which isn't great)

decreased glycogen catabolism rate
def: Decrease in the occurrence per unit time of some glycogen catabolic process

**Comment by pnrobinson** [comment]
I like Sue's suggestion but I think maybe could extend it. Occurrence per unit time sounds to me like occurrence of discrete, countable events. I know we are using this pattern for things that are measured as rates and that the inferrences might be the same, but it is ear-jarring to read "Decrease in the occurrence per unit time of some blood circulation in the kidney". Can we make a new PATO term that would work for rates as well?

**Comment by sbello** [comment]
@pnrobinson Agree that the definition is odd, particularly for blood circulation. I lifted the 'occurrence per unit time' straight from PATO. So we may want to consider if that definition needs modification.

**Comment by sbello** [comment]
How about "Change in the quantity, amount or volume of a biological process occurring per some unit of time."
Adapted from the dictionary definition of rate https://www.merriam-webster.com/dictionary/rate 

Do we ever need to use rate for non-time based rates?

**Comment by matentzn** [comment]
Terms like quantity, amount or volume seem to fit better with the actual results of process, rather than the process itself? The examples in the dictionary also seem to be material things like money or the output of a process, words written?

**Comment by sbello** [comment]
change in number of events per unit time of a biological process or output of a continuous biological process 
discussed on the call Thursday

**Comment by sbello** [comment]
Consider creating subterm patterns for rate of occurrence and rate of continuous process if and when we find a case where the single term causes issues
