### ISSUE TITLE
abnormal protein level?

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#728]

**Comment by matentzn** [comment]
use abnormal level of chemical entity pattern:
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-patterns/abnormalLevelOfChemicalEntity.yaml

We will reconcile proteins at some future point.

**Comment by pfey03** [comment]
Thanks @matentzn 
But this doesn't have all the qualifiers I need
I also need absent/decreased/increased of this basic term.

And can I add any protein or our MOD ID?
I can wait until proteins are reconciled if it's in any near future, if this makes it easier.

**Comment by matentzn** [comment]
Most of them should be there if you search on https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-patterns/README.md, like: https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedLevelOfChemicalEntity.yaml

Is there anything missing in that list?

**Comment by pfey03** [comment]
**abnormallyAbsentLevelOfChemicalEntity** is missing, or should **abnormalAbsenceOfChemicalEntity** be used for that? 

Although we have the phenotype 'abolished protein level'. I could maybe add a synonym 'abnormally absent protein'

Also, I used this list to look up patterns, but now bookmarked yours as this is incomplete https://github.com/obophenotype/upheno/tree/master/src/patterns/dosdp-dev

Thanks @matentzn, as always

**Comment by matentzn** [comment]
This is a question for the phenotype call! My feeling is they are the same (absent level and absent chemical), but maybe there are other opinions. @sbello @ybradford @dosumis

**Comment by pfey03** [comment]
ok, let's discuss it, but next Thursday, Dec 3, I have our group meeting at the same time and can't join the phenotype call, if it's scheduled for that day.

**Comment by pfey03** [comment]
Oh, sorry, don't have a dicty group call this coming Thursday, Dec 3, so I can be at the call if we want to add it to that agenda

**Comment by sbello** [comment]
I will add this to the agenda

**Comment by pfey03** [comment]
Thanks @sbello

**Comment by matentzn** [comment]
In the meeting we determined that we can in fact use abnormalAbsenceOfChemicalEntity, so I will close this issue here. @pfey03 please re-open if something is left unadressed.
