### ISSUE TITLE
Pattern for a phenotype that happens before a developmental stage

### ISSUE THREAD

**Issue by Clare72** [obophenotype/upheno#734]
DPO has a phenotype, [abnormal developmental rate](https://www.ebi.ac.uk/ols/ontologies/dpo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000450), that must occur during development (before mature adult stage).

Perhaps an 'abnormalBiologicalProcessBeforeStage' pattern, with biological_process and stage as variables?

see https://github.com/FlyBase/drosophila-phenotype-ontology/issues/22

related to #624, which requests a pattern for a phenotype at a developmental stage

**Comment by nicolevasilevsky** [comment]
@Clare72 what is your ORCID?
I'll add it to the pattern: https://github.com/obophenotype/upheno/pull/738

**Comment by nicolevasilevsky** [comment]
@Clare72 - note, you can add your ORCID to your GitHub profile (see mine for example: https://github.com/nicolevasilevsky)

**Comment by Clare72** [comment]
http://orcid.org/0000-0002-1373-1705

Thanks, have also added to my profile now!
