### ISSUE TITLE
Pattern request - increased/decreased efficacy of behavior

### ISSUE THREAD

**Issue by Clare72** [obophenotype/upheno#739]
related to https://github.com/obophenotype/upheno/pull/483 (but for behaviors)

'rate' (amount/time) is not always relevant to behavior phenotypes, see - https://github.com/FlyBase/drosophila-phenotype-ontology/issues/102

We need a pattern for how 'well' a behavior happens e.g. ability for memory to be formed/recalled

**Comment by matentzn** [comment]
I think this makes sense. @dosumis @sbello @ybradford @chris-grove ?

**Comment by sbello** [comment]
MP has many of these, typically using enhanced/impaired or increased/decreased in the labels. Some are using increased/decreased rate but these may not be the best patterns. Many have no eq.

Examples: 
MP:0020968 (http://purl.obolibrary.org/obo/MP_0020968) 
MP:0003999 (http://purl.obolibrary.org/obo/MP_0003999)
MP:0009453 (http://purl.obolibrary.org/obo/MP_0009453)

**Comment by chris-grove** [comment]
Sounds appropriate to me

**Comment by dosumis** [comment]
Discussed on uPheno call. Everyone happy with solution.  We should probably consider pushing other process phenotypes to process efficacy.
