### ISSUE TITLE
why did 'abnormal resistance to chemical entity' become 'whole organism'?

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#741]
I came about this issue
https://github.com/obophenotype/upheno/pull/491
Why simple abrnormalResistanceToChemicalEntity were changed to whole organism terms? Is a cell a whole organism and I can use them? it's weird. 

Why making this term whole organism when single cells also need to use it?

**Comment by matentzn** [comment]
They need to be distinguished - if you want to annotate that a part of the organism became abnormally resistant to a chemical (but not necessarily the whole), that needs a different pattern. I think this pattern is important for toxicological and pharmacological concerns - here we really care about how the whole organism behaves when a drug is administered, not just a single cell. 

That said - single cell organisms are covered by this pattern!

**Comment by pfey03** [comment]
OK thanks Nico!
