### ISSUE TITLE
new patterns: abnormal protein localization to cellular component

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#753]
We have a ton of phenotypes that have abnormal/decreased/increased/absent protein localization to cellular component

GO has some processes of the obvious such as
GO:0034504: protein localization to nucleus - and some others mostly for metazoans.

But we have a ton of cellular components that are not a GO process, e.g

protein localization to contractile vacuole membrane
protein localization to cytoplasmic vesicle
protein localization to secondary lysosome
protein localization to basolateral plasma membrane

AbnormalProteinLocalizationToCellularComponent

Which protein it is we have in extension later and right now in note.

Thanks

**Comment by matentzn** [comment]
I am wondering whether we should simply be using "abnormalBiologicalProcessInLocation"

[Protein Localisation](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0008104) is a biological process, and the pattern relates that process to the cellular component (protein localisation that occurs in cytoplasmatic vesicle). Or do we need a different relationship here @dosumis ?

**Comment by mah11** [comment]
- This would be useful for FYPO, so I'm for it.

@matentzn 
- I'm not at all convinced that abnormalBiologicalProcessInLocation would suffice. The problem is that "BiologicalProcessInLocation" sounds like the entire Process takes place in the Location, whereas protein localization gets protein TO a location but may (indeed, almost always does) start in some other location ... that's why the cell/organism needs to do a protein localization process at all.

IOW, we could use abnormalBiologicalProcessInLocation if we needed to say "protein localization that occurs in cytoplasmic vesicle". But what we actually need to model is "protein localization that moves some protein(s) to some cytoplasmic vesicle". We specify the location where the protein ends up, not necessarily where all of the process takes place. I wonder if we could also include an optional starting location.

AbnormalProteinLocalizationToCellularComponent makes sense to me but not wedded to it if something else would be better.

**Comment by dosumis** [comment]
> I'm not at all convinced that abnormalBiologicalProcessInLocation would suffice. The problem is that "BiologicalProcessInLocation" sounds like the entire Process takes place in the Location, whereas protein localization gets protein TO a location but may (indeed, almost always does) start in some other location ... that's why the cell/organism needs to do a protein localization process at all.

+1

There's a whole set of patterns & terms I added to GO for this.  We should check if they are still there (I fear they may have been obsoleted as seems to be the current fashion at GO).

**Comment by dosumis** [comment]
My ideal would just be to have compound GO terms for the processes and reference these (without location info in phenotype term) - as the patterns are quite complex to use for composing compound entities on the fly.

**Comment by mah11** [comment]
@dosumis me too! But GO, as you note, seems to be GOing off in directions less convenient for phenotype patterns ...

**Comment by matentzn** [comment]
Like this one? https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/establishment_of_protein_localization_to.yaml

**Comment by mah11** [comment]
yup

**Comment by LCCarmody** [comment]
I think there would be a lot of different patterns if we included the location, so I agree about making a GO process and then referencing location.  The pattern linked above may not work for all situations--as some proteins aren't expressly 'directed' and may just accumulate in a location.  We also might think of a pattern where ions are accumulated (specifically calcium, but Na+ and K+, etc) in a location, too.

**Comment by pfey03** [comment]
For my purposes, the suggested pattern would take care of my terms. I have abnormal or also some absent localizations to any cellular component in mutants. Optional start point is fine but I would have no start point from where it moves. It's typically shown to be mislocalized or absent where it should be.

How about
GO:0008104:protein localization At GO cellular component

abnormalBiologicalProcessAtCellularComponent where the BP is always GO:0008104
absentBiologicalProcessAtCellularComponent

Maybe these would be better?

**Comment by pfey03** [comment]
![proteinlocalizationto CC](https://user-images.githubusercontent.com/1349602/123660800-94e81b80-d7f9-11eb-916a-58f617b0e5f4.png)

You get an idea how many protein localization to CC terms we have. The patterns suggested above including increased/decreased should be possible?

**Comment by matentzn** [comment]
For the "normal" localisation, is this the right pattern:
https://github.com/geneontology/go-ontology/blob/master/src/design_patterns/establishment_of_protein_localization_to.yaml

ie should the pheno pattern be:

```
equivalentTo: 
  text: "'increased rate' and 'establishment of protein localization' and 'has target end location' some %s" 
  vars:
    - 'location'
```

**Comment by mah11** [comment]
I'm dithering about maybe using 'protein localization' instead of 'establishment of protein localization', because phenotypes don't always allow us to exclude 'maintenance of protein localization' (the GO structure has 'establishment' and 'maintenance' as parts of protein localization).

Otherwise fine.

**Comment by pfey03** [comment]
I agree with @mah11

**Comment by pfey03** [comment]
@matentzn what's the state of this? The establishment pattern is sub-optimal but could work. I would need qualifiers:
abnormal 
decreased
increased
absent

**Comment by matentzn** [comment]
I am not the right person for this type of question, assigning to @rays22 and @dosumis ..

**Comment by dosumis** [comment]
Agreement in uPheno call:

Use GO protein localization branch for pattern AbnormalProteinLocalization

(we don't want to deal with establishment and maintenance - assume hard to tell for phenotype - leave this for GO annotation).

Include an additional pattern AbnormalProteinLocalizationTo for cases where GO doesn't have the compound term.  This pattern should use the compound entity: 'protein locatlization' and has_target_end_location some {cellular component}

**Comment by pfey03** [comment]
absent / decreased / increased patterns are also needed at least for the AbnormalProteinLocalizationTo

**Comment by matentzn** [comment]
@rays22 this may be a good ticket to get your hands dirty on pattern definitions. We could discuss it tomorrow..

**Comment by pfey03** [comment]
@dosumis and all, I wrote an email to Pascale today to inquire if GO is willing to add several new protein localization to CC GO terms. Will let you know what she says.

**Comment by pfey03** [comment]
@dosumis @rays22 
Pascale wrote back and GO are rather obsoleting terms for which there are no shown distinct mechanisms. If adding new they want a paper and a mechanism, and I cannot do that for all these, this would be a huge project.

New patterns are the way to go: a**bnormal, decreased, increased, and absent**.

**Comment by dosumis** [comment]
> Pascale wrote back and GO are rather obsoleting terms for which there are no shown distinct mechanisms. If adding new they want a paper and a mechanism, and I cannot do that for all these, this would be a huge project.

OK.  That sucks.  I guess we're using the post-composed pattern for all then.

**Comment by rays22** [comment]
In the latest commit I have
- added one more new design pattern related phenotypes where protein localization is abnormally absent,
- changed the classes section using the term `cellular component`,
- added contributor attributions.
