### ISSUE TITLE
OccurrenceOfBiologicalProcessInLocation - can Location be GO CC?

### ISSUE THREAD

**Issue by pfey03** [obophenotype/upheno#779]
@dosumis 
I have many annotations to
abnormallyDecreasedOccurrenceOfBiologicalProcessInLocation
abnormallyIncreasedOccurrenceOfBiologicalProcessInLocation

For most, the 'Location' is a DDANAT term. 

However, I have the patterns above with several annotations where Location is a GO cellular component.

DDPHENO:0001179 | decreased actin filament polymerization at the leading edge

Is this acceptable or can BFO:0000004: independent continuant not be a GO Cellular Component?

Thanks!

**Comment by dosumis** [comment]
It's fine.

**Comment by pfey03** [comment]
So it's ok to have a GO CC? That's cool thank you @dosumis
