### ISSUE TITLE
Redo Equiv axioms for behavior terms 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#78]
Originally reported on Google Code with ID 77
```
Redo Equiv axioms for behavior terms to become: 

present and has behavior and abnormal
change from:
'has part' some 
(quality and ('inheres in' some 'fear-related behavior') and ('has component' some
abnormal))

to

'has part' some 
(present and ('inheres in' some 'fear-related behavior') and ('has component' some
abnormal))

in MP and HP
```

Reported by `vasilevs@ohsu.edu` on 2015-02-11 21:23:32

**Comment by drseb** [comment]
not sure what is gained by using present vs quality?  every individual has a fear-related behavior (this is normal). in hp we want to state that this behavior is abnormal.

closing now. please reopen if this really an issue. @nicolevasilevsky @cmungall
