### ISSUE TITLE
Document the pattern merge-replace-old workflow

### ISSUE THREAD

**Issue by matentzn** [obophenotype/upheno#786]
For MP/HP, be review DOSDP templates in bulk then we need to update the definitions.

@rays22 please document the workflow for MP carefully:

- downloading tsv
- naming tsv correctly
- adding yaml to external.tsv
- running sh run.sh make ../patterns/definitions.owl
- `sh run.sh make remove_patternised_classes`

Just a braindump above please document this well here to the ticket!

**Comment by rays22** [comment]
I need to add one more step in the document about updating the pattern files from external sources.
