### ISSUE TITLE
Add new increased volume of anatomical entity pattern

### ISSUE THREAD

**Issue by rays22** [obophenotype/upheno#793]
1. [x] add new pattern `*.yaml` for review
2. [x] get feedback
3. [x] fix or improve pattern based on feedback

* Examples:
    1. HP:0000414	[Bulbous nose](http://purl.obolibrary.org/obo/HP_0000414)
    2. XPO:0115308	[abnormally increased volume of brain](http://purl.obolibrary.org/obo/XPO_0115308)
    3. MP:0001183	[overexpanded pulmonary alveoli](http://purl.obolibrary.org/obo/MP_0001183)

**Comment by ybradford** [comment]
ZP has:
head increased volume http://purl.obolibrary.org/obo/ZP_0003908 
macrophage increased volume http://purl.obolibrary.org/obo/ZP_0142585 

Are cells included in this pattern - I can't remember from the discussion.

Orcid id 0000-0002-9900-7880

**Comment by rays22** [comment]
> Are cells included in this pattern - I can't remember from the discussion.

Yes, any anatomical entity (UBERON:0001062) class is allowed.
