### ISSUE TITLE
Add new disorganized anatomical entity pattern

### ISSUE THREAD

**Issue by rays22** [obophenotype/upheno#799]
1. [x] add new pattern `disorganizedAnatomicalEntity.yaml` for review
2. [x] get feedback
3. [x] fix or improve pattern based on feedback

* Examples:
    1. [MP:0031131	myocardial fiber disarray](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0031131)
    2. [MP:0020859	disorganized corneal epithelium](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0020859)
    3. [XPO:0115471	abnormally disorganized myotome](https://www.ebi.ac.uk/ols/ontologies/xpo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FXPO_0115471)

**Comment by ybradford** [comment]
example from ZP https://www.ebi.ac.uk/ols/ontologies/zp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZP_0000138
