### ISSUE TITLE
make sure all of the clinical modifiers (from HP) exist in PATO and add logical defs in HP to point to PATO 

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#82]
Originally reported on Google Code with ID 81

```
make PATO definition to be whatever Peter likes
compare what is in PATO to HP ‘clinical modifiers’
if any term in PATO is too generic, create a subclass that Peter confirms is correct

```

Reported by `vasilevs@ohsu.edu` on 2015-02-11 21:45:30

**Comment by nicolevasilevsky** [comment]
@pnrobinson and @drseb I'm not even sure I understand what this ticket is asking for (even though i reported it originally). Is this still something we want to do? Or should we close this?
