### ISSUE TITLE
How to search in Monarch cross-species phenotypes relations?

### ISSUE THREAD

**Issue by NuriaQueralt** [obophenotype/upheno#821]
Dear team,

I am trying to understand how to find in the Monarch graph cross-species phenotypes relations.  For instance, for a particular mouse phenotype what is the corresponding/related phenotype in human. In the upheno Github README there is this claim:

"The Monarch website uses uPheno to group data from multiple species. See for example: https://monarchinitiative.org/phenotype/MP:0003631"

But It is not clear to me how this information is represented in the graph or shown in the website, i.e. how to see which phenotype in HPO is related to MP:0003631. Could you shed some light on it?

Many thanks in advance!
With kind regards,
Núria

**Comment by matentzn** [comment]
Hey @NuriaQueralt:

1. The new version of the unified phenotype ontology with all the relations can be found here: https://ols.monarchinitiative.org/ontologies/upheno2
1. the current Monarch KG is using the old version which is based on simple "logical equivalence" between phenotypes based on their EQs. So basically, you stick together, run the reasoner, get MP:001 equivalentTo HP:001. Then the monarch ingest pipeline will do clique merging based on that (merge all phenotypes that are mutually equivalent into one node, and pick a clique leader).
1. There is a complete redesign of the Monarch KG underway, and I expect it to be browsable by the end of 2022 - this will use the above uPheno2, which will, in particular, mean, that you will have a page for MP:001, and a separate page for HP:001, and a page for the corresponding "species agnostic" version of the phenotype. Those mappings will be provided as sssom. 
1. For some version of the uPheno mappings see https://bbop-ontologies.s3.amazonaws.com/upheno/current/upheno-release/all/upheno_mapping_all.csv (not sssom yet)

**Comment by NuriaQueralt** [comment]
Hi @matentzn 

Thank you so much for your super fast reply! Some more questions below:

1. I saw on GitHub that upheno2 was under development.  How can I see via 'ols' the mapping of http://purl.obolibrary.org/obo/MP_0003631 to a term in HPO? or the relation between Microcephaly in MPO and HPO? 
2. Ah! now I remember. Thanks.
3. Nice! I built a library that generates knowledge graphs retrieving selected edges from the Monarch KG API, and represent it into Neo4j. I would like to see these MPO-HPO mappings when exploring the Neo4j graph. Is there a way in the current Monarch graph API to retrieve these cross-species mappings? Otherwise, I guess the only way I have to get them is via indirect relationship such as HPO-gene-ortholog-MPO
4. Thanks!

Thank you very much.
Kind regards,
Núria

**Comment by matentzn** [comment]
Hey Nuria, 

to get the mapping straight from the API, you should make a ticket here:
https://github.com/monarch-initiative/helpdesk/issues

and ask it there - I don't know I am afraid. When you open an issue, you should tag @kevinscharper.

**Comment by matentzn** [comment]
As for upheno, I would suggest you use the mapping set I linked under 4). 

A conservative subset can be retrieved by the "has phenotypic orthologue" relation, see https://ols.monarchinitiative.org/ontologies/upheno2/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZP_0017152&viewMode=PreferredRoots&siblings=false 

but it is very conservative, so you wont find many relationships you would expect.

**Comment by NuriaQueralt** [comment]
Thank you @matentzn !!
