### ISSUE TITLE
Add new abnormal and increased mass density patterns

### ISSUE THREAD

**Issue by rays22** [obophenotype/upheno#825]
1. [x] add new pattern `abnormalMassDensityOfAnatomicalEntity.yaml` for review
* Examples:
    1. HP:0004348	[Abnormality of bone mineral density](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0004348)
    2.  HP:0009132	[Abnormal tarsal bone mineral density](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0009132)
    3.  MP:0010119	[abnormal bone mineral density](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0010119)
2. [x] add new pattern `abnormalMassDensityOfAnatomicalEntityInLocation.yaml` for review
* Examples: ?
3. [x] add new pattern `abnormallyIncreasedMassDensityOfAnatomicalEntity.yaml` for review
* Examples:
    1. HP:0000250	[Dense calvaria](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0000250)
    2. HP:0011001	[Increased bone mineral density](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0011001)
    3. MP:0000062	[increased bone mineral density](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0000062)
4. [x] add new pattern `abnormallyIncreasedMassDensityOfAnatomicalEntityInLocation.yaml` for review
* Example:
    1. HP:0006440	[Increased density of long bone diaphyses](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0006440)
5. [x] get feedback
6. [x] fix or improve pattern based on feedback

### Notes
1. [mass density PATO:0001019](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001019&viewMode=PreferredRoots&siblings=false)
2. [increased mass density PATO:0001788](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001788)

**Comment by ybradford** [comment]
ZP:0015028 iridophore mass density, abnormal
ZP:0104264 endothelial cell artery decreased mass density, abnormal
ZP:0008359 vertebra increased mass density, abnormal

Some examples from ZP
ORCiD: 0000-0002-9900-7880
