### ISSUE TITLE
Collapsed anatomical entity pattern template

### ISSUE THREAD

**Issue by rays22** [obophenotype/upheno#848]
1. [x] add `collapsedAnatomicalEntity.yaml` DOS-DP pattern draft for community review
2. [x] get feedback
3. [x] fix or improve pattern based on feedback

* Examples:
   - [MP:0006024 collapsed Reissner membrane](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0006024)
    - [MP:0012681 collapsed brain ventricles](https://www.ebi.ac.uk/ols/ontologies/mp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMP_0012681)
    - [ZP:0000118 forebrain ventricle collapsed, abnormal](https://www.ebi.ac.uk/ols/ontologies/zp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZP_0000118)
    - [ZP:0131104 atrioventricular canal collapsed, abnormal](https://www.ebi.ac.uk/ols/ontologies/zp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZP_0131104)

**Comment by anna-anagnostop** [comment]
ok by me Anna V. Anagnostopoulos https://orcid.org/0000-0002-6490-7723
