### ISSUE TITLE
Possible NTR - Pelger-Huet anomaly in dogs

### ISSUE THREAD

**Issue by diatomsRcool** [obophenotype/upheno#863]
We need a term either in upheno or in MP to describe the Pelger-Huet anomaly in dogs. This seems to be described as an HP term (http://purl.obolibrary.org/obo/HP_0011447) is this ok to use for a dog? Do we need to add something to MP?

**Comment by matentzn** [comment]
Yes! Best request this here: https://github.com/mgijax/mammalian-phenotype-ontology/issues

**Comment by diatomsRcool** [comment]
This was added to MP. Is there any more work here?

**Comment by sbello** [comment]
I thin we can close this, terms have been added to MP in ticket https://github.com/mgijax/mammalian-phenotype-ontology/issues/3637
