### ISSUE TITLE
Documentation site mostly empty

### ISSUE THREAD

**Issue by nlharris** [obophenotype/upheno#864]
https://obophenotype.github.io/upheno/ says "Welcome to the UPHENO documentation!
It is entirely empty at the moment so look no further!"
(that's not quite true -- there is some content, just not much).

**Comment by matentzn** [comment]
Can you add a few action items here? This comment about the docs I added it because I dont want people to go to the site and start searching for in depth explanations of uPheno and how it works..

**Comment by nlharris** [comment]
I made some changes and additions, see what you think
