### ISSUE TITLE
Update cystInLocation logical definition

### ISSUE THREAD

**Issue by rays22** [obophenotype/upheno#878]
- [x] Update the logical definition of DOS-DP phenotype pattern template `cystInLocation`.
    - [PATO:0001673 cystic](https://www.ebi.ac.uk/ols/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001673)
    - [RO:0002314 characteristic of part of](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002314)

This is related to issue [revise logical definition for Renal cyst, Pulmonary cyst etc #7484](https://github.com/obophenotype/human-phenotype-ontology/issues/7484#issuecomment-1240985055))

This change was discussed on the 9/8/2022 uPheno call and agreed that the pattern should be changed to:

```
'has part' some (
    'cystic' and
    ('characteristic of part of' some %s) and
    ('has modifier' some 'abnormal')
    )
```

**Comment by matentzn** [comment]
Ok, I am not going to contradict this as the risk for the cystic pattern is super small. But generally, don't let biology dictate whether you go for "characteristic of" or "characteristic of part of". Its not a biological, its a classification concern. Think about the inferences, and if its ok that "cyst on finger" classifies under "cyst on hand" its probably ok!
