### ISSUE TITLE
issue with: dilated heart left ventricle

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#9]
Originally reported on Google Code with ID 8
```
'dilated heart left ventricle' should be a subclass of 'Abnormality of the left ventricle',
but this is not inferred.
```

Reported by `cmungall` on 2014-03-17 19:12:28

**Comment by drseb** [comment]
Looking at mammal.owl this seems to work for me. I.e.

*dilated heart left ventricle* subclass of *abnormal heart left ventricle morphology*
and
*abnormal heart left ventricle morphology* subclass of *Abnormality of the left ventricle*

reopen if you think this is still an issue.
