### ISSUE TITLE
Need nesting for apoptosis terms in MP

### ISSUE THREAD

**Issue by obophenotype-user** [obophenotype/upheno#93]
Originally reported on Google Code with ID 92
```
The MP logical defs for apoptosis terms currently are:

Example #1:
abnormal male germ cell apoptosis
'has part' some (quality and (('inheres in' some 'apoptotic process') and ('occurs
in' some 'male germ cell')) and ('has component' some abnormal))

Example #2:
abnormal lens epithelium apoptosis
'has part' some (quality and (('inheres in' some 'apoptotic process') and ('occurs
in' some 'epithelium of lens')) and ('has component' some abnormal))


Should have nesting in the format:
has part' some (quality and ('inheres in' some ('process' and ('occurs in' some 'anatomy’)))
and ('has component' some abnormal))

(ie need nesting)

```

Reported by `vasilevs@ohsu.edu` on 2015-02-11 23:36:19

**Comment by drseb** [comment]
this is still an issue in MP!!! (why?) (e.g. abnormal ovary apoptosis) at some point I fixed these automagically in HP. will search for script. 

ping @cindyJax

**Comment by cindyJax** [comment]
I thought we had already fixed these. Will check.

**Comment by drseb** [comment]
I thought so too! But it is not in mp-edit. Not sure what happened

**Comment by cindyJax** [comment]
Looks like increased and decreased apoptosis terms were converted but not abnormal.  Fixing now.

**Comment by cindyJax** [comment]
Also found a lot of messed up EQs:
'has part' some 
    ('increased rate'
     and (('inheres in' some 
        ('apoptotic process'
         and ('occurs in' some 'fetal cardiomyocyte')))
     and ('has modifier' some abnormal))
     and ('has modifier' some abnormal))
Fixing.

**Comment by cindyJax** [comment]
Very messy.  I think the "increased" script was accidentally run twice.  It's all cleaned up now.
