### ISSUE TITLE
Documentation: Dead link to OLS

### ISSUE THREAD

**Issue by hansenp** [obophenotype/upheno#942]
This section of the documentation links to the Ontology Lookup Service (OLS):
https://obophenotype.github.io/upheno/reference/core-concepts/

<img width="624" alt="image" src="https://github.com/obophenotype/upheno/assets/10495485/fe36d157-ff51-41fd-b9e2-2890d61225f4">

The link behind the text "[Unified Phenotype Ontology (uPheno)](https://www.ebi.ac.uk/ols4/ontologies/upheno)" is as follows:
https://www.ebi.ac.uk/ols4/ontologies/upheno

After clicking you will be redirected to:
https://www.ebi.ac.uk/ols4/error

UPHENO is not included in OLS4.

**Comment by matentzn** [comment]
Thank you!

I have fixed this for now by linking to: https://ols.monarchinitiative.org/ontologies/upheno2

I will keep the issue open though because we really need to load the correct uPheno2 into OLS -proper.

**Comment by hansenp** [comment]
@matentzn I think this issue could now be resolved by replacing the link

https://ols.monarchinitiative.org/ontologies/upheno2

with

https://www.ebi.ac.uk/ols4/ontologies/upheno

**Comment by matentzn** [comment]
Thank you @hansenp 

Fixed in https://github.com/obophenotype/upheno/commit/a35f0980c4e315732f23fb1a9b9c58736ed9b281
