### ISSUE TITLE
upheno v2 link broken on OBO page of upheno

### ISSUE THREAD

**Issue by hoganwr** [obophenotype/upheno#960]
The OBO page of upheno (https://obofoundry.org/ontology/upheno) says v1 has been retired, and says to use v2.

The following v2 link provided 404s: https://purl.obolibrary.org/obo/upheno/v2/upheno.owl

**Comment by matentzn** [comment]
You must have tried _just_ when we were fixing the URLs, it works now!

**Comment by hoganwr** [comment]
Can confirm :-)
